version: '2'
services:

# Right of Access (ROA) service and oracle DB mock. ROA is an internal service that allows veterans to review and grant
# access to their medical information. Veteran users must complete ROA before they can use any other mobile app.
#
  roa-services:
    image: mobileapps.vaftl.us:9250/ckm/docker-roa-service:1.0.11
    restart: on-failure
    ports:
     - "8086:8080"
    environment:
    # Use Vault
    # - VAULT_ADDR=http://vault:8200
    # - SECRET_PATH=secret/local/roa-service
    # Use Consul
    - USE_ENVCONSUL=true
    - CONSUL_SERVER=consul:8500
    - CONSUL_TOKEN=7BE784A4-7498-4469-BE2F-9C3B9444DFEF
    - CONSUL_PATH=appconfig/local/roa-service
    #- DB_ROA_USERNAME=HADB # pulled from vault
    #- DB_ROA_PASSWORD=m0ckpass01 # pulled from vault
    - SERVICE_TAGS=local
    - JAVA_OPTS=-Xms256m -Xmx512m -XX:-TieredCompilation -Xss256k -XX:+UseG1GC -XX:+UseStringDeduplication
    - JWT_SECRET=testtesttest
    - DB_ROA_URL=jdbc:oracle:thin:@mock-roa:1521:xe
    - VAMF_ENVIRONMENT=local
    #- JWT_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwRs7d+tRAuK4soDInuKp51lTTTXWN8okXR3/gSHiIB+q7vZeAGWA8ULjCYuECLde8tS6OxzZwSj/oM0kZBXuHKYq2ukWKjTEmOwlpQW4vBpX60bcx5rXwoEjbcWghK9oVWwY4OwbAJ4TYklkUHZC5buQ+8RU59u6FIWSv2N3D9VBkfYsHvp3O4aXVaE8dZ0dxldUdv/WePoLkCeUYgLsGyDg/zsZvDrX1+yvNsjNNmB/ksJSoptMv9CfyUpSXsfov+8GhBCtgzDvgn32kw79wPsrTkgnC0DRtuv+y3qCXX+ZJ6cbJ31tVus9AadUn2CrWJur6/KRYsniQaEnfA43hwIDAQAB

## ROA WEB
  roa-web:
    image: mobileapps.vaftl.us:9250/ckm/docker-roa-web
    ports:
     - "8087:80"
    environment:
    - SERVICE_TAGS=local
    - SERVICE_NAME=roa-web

  veteran-video-connect-service:
    image: 181140462490.dkr.ecr.us-east-1.amazonaws.com/ablevets/veteran-video-connect-service:3.0.0
    ports:
      - "8280:8080"
    environment:
      - constraint:nodetype==*service*
      - SERVICE_NAME=veteran-video-connect-service
      - SERVICE_TAGS=local
      - JWT_SECRET=testtesttest
      - CONSUL_SERVER=consul:8500
      - CONSUL_TOKEN=7BE784A4-7498-4469-BE2F-9C3B9444DFEF
      - CONSUL_PATH=appconfig/${VAMF_ENVIRONMENT}/veteran-video-connect-service
      - "TRACE_URL=http://localhost:9411/api/v1/spans"

# IAM SSOe Mock - Injects HTTP headers to simulate SSOe token header injection. Allows log in/out.
#
  iamssoe-proxy-mock:
    image: 181140462490.dkr.ecr.us-east-1.amazonaws.com/ablevets/idp-proxy-mock-shared:latest
    #image: local-idp
    ports:
      - 9000:80
    environment:
      - DB_HOST=iamssoe-db-mock
      - DB_PASSWORD=MySqlAdmin$$
      - API_GATEWAY_URL=http://apigateway
      - "CLIENT_LANDING=/users/v1/landing?redirect_uri="
    volumes:
      - /tmp/ssoenothing:/usr/local/openresty/nginx/conf/secured

# Mock database to store identity information
  iamssoe-db-mock:
    image: 181140462490.dkr.ecr.us-east-1.amazonaws.com/ablevets/idp-db-mock-shared:latest
    environment:
      - MYSQL_ROOT_PASSWORD=MySqlAdmin$$
      - MYSQL_DATABASE=MockUser

networks:
  default:
    external:
      name: varnextgenlocalenvironment_default
