version: '2'
services:

  var-resources:
    image: dev/var-resources:4.2.5
    ports:
     - "9092:8080"
     - "64058:64058"
    environment:
     - SERVICE_64058_IGNORE=true
     - SERVICE_TAGS=local
     - SERVICE_NAME=var-resources
     - CONSUL_SERVER=consul:8500
     - CONSUL_TOKEN=7BE784A4-7498-4469-BE2F-9C3B9444DFEF
     - CONSUL_PATH=appconfig/local/var-resources
     - mock.mvi=false
     - JWT_SECRET=testtesttest
     - JAVA_OPTS=-XX:+CMSClassUnloadingEnabled -Xrs -Dcom.sun.xml.ws.transport.http.client.HttpTransportPipe.dump=true -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=64058

  var-web:
     image: dev/var-web:4.2.5
     ports:
       - "9090:80"
     environment:
       - SERVICE_TAGS=local
       - SERVICE_NAME=var-web

networks:
  default:
    external:
      name: varnextgenlocalenvironment_default