version: '2'
services:
  mock-roa:
    image: mobileapps.vaftl.us:9250/ckm/docker-roa-mock:1.0.3
    ports:
    - "1521"

  var-mongo-db-mock:
    image: 181140462490.dkr.ecr.us-east-1.amazonaws.com/ablevets/var-mongo-db-mock:1.0.0
    #image: dev/var-mongo-db-mock
    ports:
      - "27017:27017"
    environment:
      - constraint:nodetype==*service*
      - SERVICE_NAME=var-mongo-db-mock
      - SERVICE_TAGS=local
      - JWT_SECRET=testtesttest
      - CONSUL_SERVER=consul:8500
      - CONSUL_TOKEN=${CONSUL_MASTER_TOKEN}
      - CONSUL_PATH=appconfig/${VAMF_ENVIRONMENT}/var-mongo-db-mock

  var-oracle-db-mock:
    image: sath89/oracle-xe-11g:latest
    ports:
      - "1521:1521"
    volumes:
      - ./var-oracle-db-mock:/docker-entrypoint-initdb.d
    environment:
      - constraint:nodetype==*service*
      - SERVICE_NAME=var-oracle-db-mock
      - SERVICE_TAGS=local
      - JWT_SECRET=testtesttest
      - CONSUL_SERVER=consul:8500
      - CONSUL_TOKEN=${CONSUL_MASTER_TOKEN}
      - CONSUL_PATH=appconfig/${VAMF_ENVIRONMENT}/var-oracle-db-mock

  video-visits-mongo-mock:
    image: 181140462490.dkr.ecr.us-east-1.amazonaws.com/ablevets/video-visits-mongo-mock:latest
    ports:
      - "27015:27017"
    environment:
      - constraint:nodetype==*service*
      - SERVICE_NAME=video-visits-mongo-mock
      - SERVICE_TAGS=local
      - JWT_SECRET=testtesttest
      - CONSUL_SERVER=consul:8500
      - CONSUL_TOKEN=${CONSUL_MASTER_TOKEN}
      - CONSUL_PATH=appconfig/${VAMF_ENVIRONMENT}/video-visits-mongo-mock


# fixtures used for upcoming shared services

# Mongo mock for quartz and notifications, username/pass authentication turned on by default
# SSL turned off by default
#  mongo:
#    image: mobileapps.vaftl.us:9250/ckm/mock-mongo:1.0.0
#    expose:
#     - "27017"
#    ports:
#     - "27017"
#    environment:
#    - MONGODB_ADMIN_USER=admin
#    - MONGODB_ADMIN_PASS=adminpass
#    - MONGODB_APPLICATION_DATABASE=notificationsdb, remindersdb, taskresourcesdb
#    - MONGODB_APPLICATION_USER=testuser
#    - MONGODB_APPLICATION_PASS=testpass
#    - SSL_ENABLED=false
#    - AUTH_ENABLED=true
#    - JOURNALING=true

networks:
  default:
    external:
      name: varnextgenlocalenvironment_default