version: '2'
services:

  scheduling-manager-resources:
#    image: dev/scheduling-manager-resources
    image: 181140462490.dkr.ecr.us-east-1.amazonaws.com/ablevets/scheduling-manager-resources:3.0.0
    ports:
     - "9070:8080"
     - "64059:64059"
    environment:
     - SERVICE_64059_IGNORE=true
     - SERVICE_TAGS=local
     - SERVICE_NAME=scheduling-manager-resources
     - CONSUL_SERVER=consul:8500
     - CONSUL_TOKEN=7BE784A4-7498-4469-BE2F-9C3B9444DFEF
     - CONSUL_PATH=appconfig/local/scheduling-manager-resources
     - JWT_SECRET=testtesttest
     - JAVA_OPTS=-XX:+CMSClassUnloadingEnabled -Xrs -Dcom.sun.xml.ws.transport.http.client.HttpTransportPipe.dump=true -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=64059

  scheduling-manager-web:
#     image: dev/scheduling-manager-web
     image: 181140462490.dkr.ecr.us-east-1.amazonaws.com/ablevets/scheduling-manager-web:3.0.0
     ports:
       - "9071:80"
     environment:
       - SERVICE_TAGS=local
       - SERVICE_NAME=scheduling-manager-web

networks:
  default:
    external:
      name: varnextgenlocalenvironment_default