version: '2'
services:
  var-mongo-db-mock:
    image: dev/var-mongo-db-mock
    ports:
      - "27016:27017"
    environment:
      - constraint:nodetype==*service*
      - SERVICE_NAME=var-mongo-db-mock
      - SERVICE_TAGS=local
      - JWT_SECRET=testtesttest
      - CONSUL_SERVER=consul:8500
      - CONSUL_TOKEN=${CONSUL_MASTER_TOKEN}
      - CONSUL_PATH=appconfig/${VAMF_ENVIRONMENT}/var-mongo-db-mock

  var-oracle-db-mock:
    image: sath89/oracle-xe-11g
    ports:
      - "1521:1521"
    volumes:
      - ./var-oracle-db-mock:/docker-entrypoint-initdb.d
    environment:
      - constraint:nodetype==*service*
      - SERVICE_NAME=var-oracle-db-mock
      - SERVICE_TAGS=local
      - JWT_SECRET=testtesttest
      - CONSUL_SERVER=consul:8500
      - CONSUL_TOKEN=${CONSUL_MASTER_TOKEN}
      - CONSUL_PATH=appconfig/${VAMF_ENVIRONMENT}/var-oracle-db-mock

  video-visits-mongo-mock:
    image: 181140462490.dkr.ecr.us-east-1.amazonaws.com/ablevets/video-visits-mongo-mock:latest
    ports:
      - "27015:27017"
    environment:
      - constraint:nodetype==*service*
      - SERVICE_NAME=video-visits-mongo-mock
      - SERVICE_TAGS=local
      - JWT_SECRET=testtesttest
      - CONSUL_SERVER=consul:8500
      - CONSUL_TOKEN=${CONSUL_MASTER_TOKEN}
      - CONSUL_PATH=appconfig/${VAMF_ENVIRONMENT}/video-visits-mongo-mock


networks:
  default:
    external:
      name: varnextgenlocalenvironment_default