#!/usr/bin/env bash

. composed-services.sh

function logs_core(){
    echo "\nOpening docker logs for NextGen core services... \n"
    docker-compose logs -f consul "${core[@]}"
}

function logs_fixtures(){
    echo "\nOpening docker logs for fixtures... \n"
    docker-compose logs -f "${fixtures[@]}"
}

function logs_data_seed(){
    echo "\nOpening docker logs for data seed... \n"
    docker-compose logs -f var-mongo-data-seed
}

function logs_shared_services(){
    echo "\nOpening docker logs for shared services... \n"
    docker-compose logs -f consul "${ss[@]}"
}

function logs_vet(){
    echo "\nOpening docker logs for vet services... \n"
    docker-compose logs -f "${vet[@]}"
}

function logs_staff(){
    echo "\nOpening docker logs for staff services... \n"
    docker-compose logs -f "${staff[@]}"
}

function logs_var(){
    echo "\nOpening docker logs for VAR... \n"
    docker-compose logs -f "${var[@]}"
}

function logs_sm(){
    echo "\nOpening docker logs for SM... \n"
    docker-compose logs -f "${sm[@]}"
}

function logs_via(){
    echo "\nOpening docker logs for VIA... \n"
    docker-compose logs -f "${via[@]}"
}

while [[ "$#" > 0 ]]; do case $1 in
  c|core|-c|--core) logs_core; shift;;
  f|-f|--fixtures) logs_fixtures; shift;;
  s|ss|-s|--shared-services) logs_shared_services; shift;;
  d|data|-d|--data-seed) logs_data_seed; shift;;
  v|vet|-v|--vet) logs_vet; shift;;
  staff|--staff) logs_staff; shift;;
  via|--via) logs_via; shift;;
  var|--var) logs_var; shift;;
  sm|--sm) logs_sm; shift;;
  *) docker-compose logs -f $1;
esac; shift; done
