#!/usr/bin/env bash

. app.env

. composed-services.sh

function stop_fixtures(){
    docker-compose rm -v -s -f "${fixtures[@]}"
}

function stop_via(){
    docker-compose rm -v -s -f "${via[@]}"
}

function stop_core(){
    docker-compose rm -v -s -f "${core[@]}"
    docker-compose rm -v -s -f "consul"
}

function stop_data_seed(){
    docker-compose rm -v -s -f var-mongo-data-seed
}

function stop_shared_services(){
    docker-compose rm -v -s -f "${ss[@]}"
}

function stop_vet(){
    docker-compose rm -v -s -f "${vet[@]}"
}

function stop_staff(){
    docker-compose rm -v -s -f "${staff[@]}"
}

function stop_var(){
    docker-compose rm -v -s -f "${var[@]}"
}

function stop_sm(){
    docker-compose rm -v -s -f "${sm[@]}"
}

function stop_vats(){
    docker-compose rm -v -s -f "${vats[@]}"
}

function stop_all(){
    stop_core;
    stop_fixtures;
    stop_data_seed;
    stop_shared_services;
    stop_vet;
    stop_staff;
    stop_var;
    stop_sm;
    stop_vats;
}

while [[ "$#" > 0 ]]; do case $1 in
  a|all|-a|--all) stop_all; shift;;
  c|core|-c|--core) stop_core; shift;;
  f|fixtures|-f|--fixtures) stop_fixtures; shift;;
  via|--via) stop_via; shift;;
  s|ss|-s|--shared-services) stop_shared_services; shift;;
  v|vet|-v|--vet) stop_vet; shift;;
  staff|--staff) stop_staff; shift;;
  var|--var) stop_var; shift;;
  sm|--sm) stop_sm; shift;;
  vats|--vats) stop_vats; shift;;
  *) echo "Unknown parameter: $1"; exit 1;;
esac; done

echo -e "\nCleaning up dangling volumes"
docker volume rm $(docker volume ls -f dangling=true -q)

# removes cache file created by docker from var-oracle-db-mock
echo -e "\nCleaning up generated docker cache file from oracle-db"

rm -f ./var-oracle-db-mock/.cache

