
package gov.va.pie.nvacdwvista.hl7v3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "VAIdMPort", targetNamespace = "http://vaww.oed.oit.va.gov")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VAIdMPort {


    /**
     * 
     * @param inboundXML
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "PRPA_IN201309UV02")
    @WebResult(name = "PRPA_IN201310UV02", targetNamespace = "http://vaww.oed.oit.va.gov", partName = "returnXML")
    public Object prpaIN201309UV02(
        @WebParam(name = "PRPA_IN201309UV02", targetNamespace = "http://vaww.oed.oit.va.gov", partName = "inboundXML")
        Object inboundXML);

    /**
     * 
     * @param inboundXML
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "PRPA_IN201305UV02")
    @WebResult(name = "PRPA_IN201306UV02", targetNamespace = "http://vaww.oed.oit.va.gov", partName = "returnXML")
    public Object prpaIN201305UV02(
        @WebParam(name = "PRPA_IN201305UV02", targetNamespace = "http://vaww.oed.oit.va.gov", partName = "inboundXML")
        Object inboundXML);

    /**
     * 
     * @param inboundXML
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "PRPA_IN201301UV02")
    @WebResult(name = "MCCI_IN000002UV01", targetNamespace = "http://vaww.oed.oit.va.gov", partName = "returnXML")
    public Object prpaIN201301UV02(
        @WebParam(name = "PRPA_IN201301UV02", targetNamespace = "http://vaww.oed.oit.va.gov", partName = "inboundXML")
        Object inboundXML);

    /**
     * 
     * @param inboundXML
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "PRPA_IN201302UV02")
    @WebResult(name = "MCCI_IN000002UV01", targetNamespace = "http://vaww.oed.oit.va.gov", partName = "returnXML")
    public Object prpaIN201302UV02(
        @WebParam(name = "PRPA_IN201302UV02", targetNamespace = "http://vaww.oed.oit.va.gov", partName = "inboundXML")
        Object inboundXML);

    /**
     * 
     * @param inboundXML
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "PRPA_IN201304UV02")
    @WebResult(name = "MCCI_IN000002UV01", targetNamespace = "http://vaww.oed.oit.va.gov", partName = "returnXML")
    public Object prpaIN201304UV02(
        @WebParam(name = "PRPA_IN201304UV02", targetNamespace = "http://vaww.oed.oit.va.gov", partName = "inboundXML")
        Object inboundXML);

}
