
package gov.va.pie.nvacdwvista.hl7v3;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import gov.va.pie.common.service.PieLogService;
import gov.va.pie.common.utils.CommonConstants;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "VAIdM", targetNamespace = "urn:hl7-org:v3", wsdlLocation = "file:/C:/_PMAS/_i7/_ant/IdmHl7v3.wsdl")
public class VAMVI
    extends Service
{

    private final static URL VAIDM_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(gov.va.pie.nvacdwvista.hl7v3.VAMVI.class.getName());
    
    

    static {
    	
    	PieLogService pieLogService = new PieLogService();
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = gov.va.pie.nvacdwvista.hl7v3.VAMVI.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/_PMAS/_i7/_ant/IdmHl7v3.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/_PMAS/_i7/_ant/IdmHl7v3.wsdl', retrying as a local file");
            pieLogService.recordDetails(e, CommonConstants.LOG_WARN);
        }
        VAIDM_WSDL_LOCATION = url;
    }

    public VAMVI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VAMVI() {
        super(VAIDM_WSDL_LOCATION, new QName("urn:hl7-org:v3", "VAIdM"));
    }

    /**
     * 
     * @return
     *     returns VAMVIPort
     */
    @WebEndpoint(name = "VAMVIPort")
    public VAMVIPort getVAMVIPort() {
        return super.getPort(new QName("urn:hl7-org:v3", "VAIdMPort"), VAMVIPort.class);
    }
    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VAMVIPort
     */
    @WebEndpoint(name = "VAMVIPort")
    public VAMVIPort getVAMVIPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:hl7-org:v3", "VAMVIPort"), VAMVIPort.class, features);
    }

}
