//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 03:53:36 PM EDT 
//


package gov.va.pie.ppms.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CareSiteType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CareSiteType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Facility"/&gt;
 *     &lt;enumeration value="Pharmacy"/&gt;
 *     &lt;enumeration value="Clinic"/&gt;
 *     &lt;enumeration value="Ward"/&gt;
 *     &lt;enumeration value="Unit Dose Cart"/&gt;
 *     &lt;enumeration value="Community Living Center"/&gt;
 *     &lt;enumeration value="Spinal Cord Injury Unit"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CareSiteType")
@XmlEnum
public enum CareSiteType {

    @XmlEnumValue("Facility")
    FACILITY("Facility"),
    @XmlEnumValue("Pharmacy")
    PHARMACY("Pharmacy"),
    @XmlEnumValue("Clinic")
    CLINIC("Clinic"),
    @XmlEnumValue("Ward")
    WARD("Ward"),
    @XmlEnumValue("Unit Dose Cart")
    UNIT_DOSE_CART("Unit Dose Cart"),
    @XmlEnumValue("Community Living Center")
    COMMUNITY_LIVING_CENTER("Community Living Center"),
    @XmlEnumValue("Spinal Cord Injury Unit")
    SPINAL_CORD_INJURY_UNIT("Spinal Cord Injury Unit");
    private final String value;

    CareSiteType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CareSiteType fromValue(String v) {
        for (CareSiteType c: CareSiteType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
