//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 03:53:36 PM EDT 
//


package gov.va.pie.ppms.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContactInfoType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ContactInfoType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Email"/&gt;
 *     &lt;enumeration value="Telecom"/&gt;
 *     &lt;enumeration value="Pager"/&gt;
 *     &lt;enumeration value="Web Address"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ContactInfoType")
@XmlEnum
public enum ContactInfoType {

    @XmlEnumValue("Email")
    EMAIL("Email"),
    @XmlEnumValue("Telecom")
    TELECOM("Telecom"),
    @XmlEnumValue("Pager")
    PAGER("Pager"),
    @XmlEnumValue("Web Address")
    WEB_ADDRESS("Web Address");
    private final String value;

    ContactInfoType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ContactInfoType fromValue(String v) {
        for (ContactInfoType c: ContactInfoType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
