//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 03:53:36 PM EDT 
//


package gov.va.pie.ppms.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DeaSchedulePrivilege complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeaSchedulePrivilege"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DeaNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ExpirationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="VerificationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="Verifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="HasScheduleIi" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="HasScheduleIiNonNarcotic" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="HasScheduleIii" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="HasScheduleIiiNonNarcotic" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="HasScheduleIv" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="HasScheduleV" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeaSchedulePrivilege", propOrder = {
    "deaNumber",
    "expirationDate",
    "verificationDate",
    "verifier",
    "hasScheduleIi",
    "hasScheduleIiNonNarcotic",
    "hasScheduleIii",
    "hasScheduleIiiNonNarcotic",
    "hasScheduleIv",
    "hasScheduleV"
})
public class DeaSchedulePrivilege {

    @XmlElement(name = "DeaNumber", required = true)
    protected String deaNumber;
    @XmlElement(name = "ExpirationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar expirationDate;
    @XmlElement(name = "VerificationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar verificationDate;
    @XmlElement(name = "Verifier")
    protected String verifier;
    @XmlElement(name = "HasScheduleIi")
    protected Boolean hasScheduleIi;
    @XmlElement(name = "HasScheduleIiNonNarcotic")
    protected Boolean hasScheduleIiNonNarcotic;
    @XmlElement(name = "HasScheduleIii")
    protected Boolean hasScheduleIii;
    @XmlElement(name = "HasScheduleIiiNonNarcotic")
    protected Boolean hasScheduleIiiNonNarcotic;
    @XmlElement(name = "HasScheduleIv")
    protected Boolean hasScheduleIv;
    @XmlElement(name = "HasScheduleV")
    protected Boolean hasScheduleV;

    /**
     * Gets the value of the deaNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeaNumber() {
        return deaNumber;
    }

    /**
     * Sets the value of the deaNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeaNumber(String value) {
        this.deaNumber = value;
    }

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpirationDate(XMLGregorianCalendar value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the verificationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVerificationDate() {
        return verificationDate;
    }

    /**
     * Sets the value of the verificationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVerificationDate(XMLGregorianCalendar value) {
        this.verificationDate = value;
    }

    /**
     * Gets the value of the verifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerifier() {
        return verifier;
    }

    /**
     * Sets the value of the verifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerifier(String value) {
        this.verifier = value;
    }

    /**
     * Gets the value of the hasScheduleIi property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasScheduleIi() {
        return hasScheduleIi;
    }

    /**
     * Sets the value of the hasScheduleIi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasScheduleIi(Boolean value) {
        this.hasScheduleIi = value;
    }

    /**
     * Gets the value of the hasScheduleIiNonNarcotic property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasScheduleIiNonNarcotic() {
        return hasScheduleIiNonNarcotic;
    }

    /**
     * Sets the value of the hasScheduleIiNonNarcotic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasScheduleIiNonNarcotic(Boolean value) {
        this.hasScheduleIiNonNarcotic = value;
    }

    /**
     * Gets the value of the hasScheduleIii property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasScheduleIii() {
        return hasScheduleIii;
    }

    /**
     * Sets the value of the hasScheduleIii property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasScheduleIii(Boolean value) {
        this.hasScheduleIii = value;
    }

    /**
     * Gets the value of the hasScheduleIiiNonNarcotic property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasScheduleIiiNonNarcotic() {
        return hasScheduleIiiNonNarcotic;
    }

    /**
     * Sets the value of the hasScheduleIiiNonNarcotic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasScheduleIiiNonNarcotic(Boolean value) {
        this.hasScheduleIiiNonNarcotic = value;
    }

    /**
     * Gets the value of the hasScheduleIv property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasScheduleIv() {
        return hasScheduleIv;
    }

    /**
     * Sets the value of the hasScheduleIv property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasScheduleIv(Boolean value) {
        this.hasScheduleIv = value;
    }

    /**
     * Gets the value of the hasScheduleV property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasScheduleV() {
        return hasScheduleV;
    }

    /**
     * Sets the value of the hasScheduleV property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasScheduleV(Boolean value) {
        this.hasScheduleV = value;
    }

}
