//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 03:53:36 PM EDT 
//


package gov.va.pie.ppms.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EmrSystemType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EmrSystemType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="None"/&gt;
 *     &lt;enumeration value="Allscripts"/&gt;
 *     &lt;enumeration value="AthenaHealth"/&gt;
 *     &lt;enumeration value="Cerner"/&gt;
 *     &lt;enumeration value="eClinicalWorks"/&gt;
 *     &lt;enumeration value="Epic"/&gt;
 *     &lt;enumeration value="Fusion"/&gt;
 *     &lt;enumeration value="GE Healthcare"/&gt;
 *     &lt;enumeration value="Greenway"/&gt;
 *     &lt;enumeration value="Netsmart"/&gt;
 *     &lt;enumeration value="Practice"/&gt;
 *     &lt;enumeration value="Not Sure"/&gt;
 *     &lt;enumeration value="Other"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EmrSystemType")
@XmlEnum
public enum EmrSystemType {

    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("Allscripts")
    ALLSCRIPTS("Allscripts"),
    @XmlEnumValue("AthenaHealth")
    ATHENA_HEALTH("AthenaHealth"),
    @XmlEnumValue("Cerner")
    CERNER("Cerner"),
    @XmlEnumValue("eClinicalWorks")
    E_CLINICAL_WORKS("eClinicalWorks"),
    @XmlEnumValue("Epic")
    EPIC("Epic"),
    @XmlEnumValue("Fusion")
    FUSION("Fusion"),
    @XmlEnumValue("GE Healthcare")
    GE_HEALTHCARE("GE Healthcare"),
    @XmlEnumValue("Greenway")
    GREENWAY("Greenway"),
    @XmlEnumValue("Netsmart")
    NETSMART("Netsmart"),
    @XmlEnumValue("Practice")
    PRACTICE("Practice"),
    @XmlEnumValue("Not Sure")
    NOT_SURE("Not Sure"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    EmrSystemType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EmrSystemType fromValue(String v) {
        for (EmrSystemType c: EmrSystemType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
