//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 03:53:36 PM EDT 
//


package gov.va.pie.ppms.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ethnicity.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Ethnicity"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Unknown"/&gt;
 *     &lt;enumeration value="American Indian or Alaska Native"/&gt;
 *     &lt;enumeration value="Asian"/&gt;
 *     &lt;enumeration value="Black or African American"/&gt;
 *     &lt;enumeration value="Decline to Answer"/&gt;
 *     &lt;enumeration value="Hispanic or Latino"/&gt;
 *     &lt;enumeration value="Native Hawaiian or Other Pacific Islander"/&gt;
 *     &lt;enumeration value="No Preference"/&gt;
 *     &lt;enumeration value="Not Hispanic or Latino"/&gt;
 *     &lt;enumeration value="Other"/&gt;
 *     &lt;enumeration value="White"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "Ethnicity")
@XmlEnum
public enum Ethnicity {

    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown"),
    @XmlEnumValue("American Indian or Alaska Native")
    AMERICAN_INDIAN_OR_ALASKA_NATIVE("American Indian or Alaska Native"),
    @XmlEnumValue("Asian")
    ASIAN("Asian"),
    @XmlEnumValue("Black or African American")
    BLACK_OR_AFRICAN_AMERICAN("Black or African American"),
    @XmlEnumValue("Decline to Answer")
    DECLINE_TO_ANSWER("Decline to Answer"),
    @XmlEnumValue("Hispanic or Latino")
    HISPANIC_OR_LATINO("Hispanic or Latino"),
    @XmlEnumValue("Native Hawaiian or Other Pacific Islander")
    NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER("Native Hawaiian or Other Pacific Islander"),
    @XmlEnumValue("No Preference")
    NO_PREFERENCE("No Preference"),
    @XmlEnumValue("Not Hispanic or Latino")
    NOT_HISPANIC_OR_LATINO("Not Hispanic or Latino"),
    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("White")
    WHITE("White");
    private final String value;

    Ethnicity(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Ethnicity fromValue(String v) {
        for (Ethnicity c: Ethnicity.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
