//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 03:53:36 PM EDT 
//


package gov.va.pie.ppms.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HealthProviderType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HealthProviderType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="None"/&gt;
 *     &lt;enumeration value="Community Hospital"/&gt;
 *     &lt;enumeration value="External Laboratory"/&gt;
 *     &lt;enumeration value="Community Service"/&gt;
 *     &lt;enumeration value="Home Health Care"/&gt;
 *     &lt;enumeration value="Radiology"/&gt;
 *     &lt;enumeration value="Services"/&gt;
 *     &lt;enumeration value="External Support Group"/&gt;
 *     &lt;enumeration value="Rehabilitation"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "HealthProviderType")
@XmlEnum
public enum HealthProviderType {

    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("Community Hospital")
    COMMUNITY_HOSPITAL("Community Hospital"),
    @XmlEnumValue("External Laboratory")
    EXTERNAL_LABORATORY("External Laboratory"),
    @XmlEnumValue("Community Service")
    COMMUNITY_SERVICE("Community Service"),
    @XmlEnumValue("Home Health Care")
    HOME_HEALTH_CARE("Home Health Care"),
    @XmlEnumValue("Radiology")
    RADIOLOGY("Radiology"),
    @XmlEnumValue("Services")
    SERVICES("Services"),
    @XmlEnumValue("External Support Group")
    EXTERNAL_SUPPORT_GROUP("External Support Group"),
    @XmlEnumValue("Rehabilitation")
    REHABILITATION("Rehabilitation");
    private final String value;

    HealthProviderType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HealthProviderType fromValue(String v) {
        for (HealthProviderType c: HealthProviderType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
