//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 03:53:36 PM EDT 
//


package gov.va.pie.ppms.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Individual complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Individual"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Ethnicity" type="{https://ppms.va.gov/exchange/ccn/2.0}Ethnicity" minOccurs="0"/&gt;
 *         &lt;element name="Gender" type="{https://ppms.va.gov/exchange/ccn/2.0}GenderType" minOccurs="0"/&gt;
 *         &lt;element name="Religion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IsAcceptingNewPatients" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="IsPrimaryCareProvider" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="IsPrimaryCareProviderAcceptingVa" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ProviderServices" type="{https://ppms.va.gov/exchange/ccn/2.0}ProviderServices" minOccurs="0"/&gt;
 *         &lt;element name="BoardCertifications" type="{https://ppms.va.gov/exchange/ccn/2.0}BoardCertifications" minOccurs="0"/&gt;
 *         &lt;element name="DeaNumbers" type="{https://ppms.va.gov/exchange/ccn/2.0}DeaSchedulePrivileges" minOccurs="0"/&gt;
 *         &lt;element name="IndividualProviderPrivileges" type="{https://ppms.va.gov/exchange/ccn/2.0}IndividualProviderPrivileges" minOccurs="0"/&gt;
 *         &lt;element name="MedicalEducations" type="{https://ppms.va.gov/exchange/ccn/2.0}MedicalEducations" minOccurs="0"/&gt;
 *         &lt;element name="ProviderCredentials" type="{https://ppms.va.gov/exchange/ccn/2.0}ProviderCredentials" minOccurs="0"/&gt;
 *         &lt;element name="ProviderOtherNames" type="{https://ppms.va.gov/exchange/ccn/2.0}ProviderOtherNames" minOccurs="0"/&gt;
 *         &lt;element name="Contacts" type="{https://ppms.va.gov/exchange/ccn/2.0}Contacts" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Individual", propOrder = {
    "firstName",
    "middleName",
    "lastName",
    "ethnicity",
    "gender",
    "religion",
    "isAcceptingNewPatients",
    "isPrimaryCareProvider",
    "isPrimaryCareProviderAcceptingVa",
    "providerServices",
    "boardCertifications",
    "deaNumbers",
    "individualProviderPrivileges",
    "medicalEducations",
    "providerCredentials",
    "providerOtherNames",
    "contacts"
})
public class Individual {

    @XmlElement(name = "FirstName")
    protected String firstName;
    @XmlElement(name = "MiddleName")
    protected String middleName;
    @XmlElement(name = "LastName")
    protected String lastName;
    @XmlElement(name = "Ethnicity")
    @XmlSchemaType(name = "string")
    protected Ethnicity ethnicity;
    @XmlElement(name = "Gender")
    @XmlSchemaType(name = "string")
    protected GenderType gender;
    @XmlElement(name = "Religion")
    protected String religion;
    @XmlElement(name = "IsAcceptingNewPatients")
    protected Boolean isAcceptingNewPatients;
    @XmlElement(name = "IsPrimaryCareProvider")
    protected Boolean isPrimaryCareProvider;
    @XmlElement(name = "IsPrimaryCareProviderAcceptingVa")
    protected Boolean isPrimaryCareProviderAcceptingVa;
    @XmlElement(name = "ProviderServices")
    protected ProviderServices providerServices;
    @XmlElement(name = "BoardCertifications")
    protected BoardCertifications boardCertifications;
    @XmlElement(name = "DeaNumbers")
    protected DeaSchedulePrivileges deaNumbers;
    @XmlElement(name = "IndividualProviderPrivileges")
    protected IndividualProviderPrivileges individualProviderPrivileges;
    @XmlElement(name = "MedicalEducations")
    protected MedicalEducations medicalEducations;
    @XmlElement(name = "ProviderCredentials")
    protected ProviderCredentials providerCredentials;
    @XmlElement(name = "ProviderOtherNames")
    protected ProviderOtherNames providerOtherNames;
    @XmlElement(name = "Contacts")
    protected Contacts contacts;

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the ethnicity property.
     * 
     * @return
     *     possible object is
     *     {@link Ethnicity }
     *     
     */
    public Ethnicity getEthnicity() {
        return ethnicity;
    }

    /**
     * Sets the value of the ethnicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ethnicity }
     *     
     */
    public void setEthnicity(Ethnicity value) {
        this.ethnicity = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link GenderType }
     *     
     */
    public GenderType getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenderType }
     *     
     */
    public void setGender(GenderType value) {
        this.gender = value;
    }

    /**
     * Gets the value of the religion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReligion() {
        return religion;
    }

    /**
     * Sets the value of the religion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReligion(String value) {
        this.religion = value;
    }

    /**
     * Gets the value of the isAcceptingNewPatients property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsAcceptingNewPatients() {
        return isAcceptingNewPatients;
    }

    /**
     * Sets the value of the isAcceptingNewPatients property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsAcceptingNewPatients(Boolean value) {
        this.isAcceptingNewPatients = value;
    }

    /**
     * Gets the value of the isPrimaryCareProvider property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPrimaryCareProvider() {
        return isPrimaryCareProvider;
    }

    /**
     * Sets the value of the isPrimaryCareProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPrimaryCareProvider(Boolean value) {
        this.isPrimaryCareProvider = value;
    }

    /**
     * Gets the value of the isPrimaryCareProviderAcceptingVa property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPrimaryCareProviderAcceptingVa() {
        return isPrimaryCareProviderAcceptingVa;
    }

    /**
     * Sets the value of the isPrimaryCareProviderAcceptingVa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPrimaryCareProviderAcceptingVa(Boolean value) {
        this.isPrimaryCareProviderAcceptingVa = value;
    }

    /**
     * Gets the value of the providerServices property.
     * 
     * @return
     *     possible object is
     *     {@link ProviderServices }
     *     
     */
    public ProviderServices getProviderServices() {
        return providerServices;
    }

    /**
     * Sets the value of the providerServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProviderServices }
     *     
     */
    public void setProviderServices(ProviderServices value) {
        this.providerServices = value;
    }

    /**
     * Gets the value of the boardCertifications property.
     * 
     * @return
     *     possible object is
     *     {@link BoardCertifications }
     *     
     */
    public BoardCertifications getBoardCertifications() {
        return boardCertifications;
    }

    /**
     * Sets the value of the boardCertifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link BoardCertifications }
     *     
     */
    public void setBoardCertifications(BoardCertifications value) {
        this.boardCertifications = value;
    }

    /**
     * Gets the value of the deaNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link DeaSchedulePrivileges }
     *     
     */
    public DeaSchedulePrivileges getDeaNumbers() {
        return deaNumbers;
    }

    /**
     * Sets the value of the deaNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeaSchedulePrivileges }
     *     
     */
    public void setDeaNumbers(DeaSchedulePrivileges value) {
        this.deaNumbers = value;
    }

    /**
     * Gets the value of the individualProviderPrivileges property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualProviderPrivileges }
     *     
     */
    public IndividualProviderPrivileges getIndividualProviderPrivileges() {
        return individualProviderPrivileges;
    }

    /**
     * Sets the value of the individualProviderPrivileges property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualProviderPrivileges }
     *     
     */
    public void setIndividualProviderPrivileges(IndividualProviderPrivileges value) {
        this.individualProviderPrivileges = value;
    }

    /**
     * Gets the value of the medicalEducations property.
     * 
     * @return
     *     possible object is
     *     {@link MedicalEducations }
     *     
     */
    public MedicalEducations getMedicalEducations() {
        return medicalEducations;
    }

    /**
     * Sets the value of the medicalEducations property.
     * 
     * @param value
     *     allowed object is
     *     {@link MedicalEducations }
     *     
     */
    public void setMedicalEducations(MedicalEducations value) {
        this.medicalEducations = value;
    }

    /**
     * Gets the value of the providerCredentials property.
     * 
     * @return
     *     possible object is
     *     {@link ProviderCredentials }
     *     
     */
    public ProviderCredentials getProviderCredentials() {
        return providerCredentials;
    }

    /**
     * Sets the value of the providerCredentials property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProviderCredentials }
     *     
     */
    public void setProviderCredentials(ProviderCredentials value) {
        this.providerCredentials = value;
    }

    /**
     * Gets the value of the providerOtherNames property.
     * 
     * @return
     *     possible object is
     *     {@link ProviderOtherNames }
     *     
     */
    public ProviderOtherNames getProviderOtherNames() {
        return providerOtherNames;
    }

    /**
     * Sets the value of the providerOtherNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProviderOtherNames }
     *     
     */
    public void setProviderOtherNames(ProviderOtherNames value) {
        this.providerOtherNames = value;
    }

    /**
     * Gets the value of the contacts property.
     * 
     * @return
     *     possible object is
     *     {@link Contacts }
     *     
     */
    public Contacts getContacts() {
        return contacts;
    }

    /**
     * Sets the value of the contacts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contacts }
     *     
     */
    public void setContacts(Contacts value) {
        this.contacts = value;
    }

}
