//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 03:53:36 PM EDT 
//


package gov.va.pie.ppms.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Npi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Npi"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="EntityTypeCode" type="{https://ppms.va.gov/exchange/ccn/2.0}NpiType"/&gt;
 *         &lt;element name="SoleProprieter" type="{https://ppms.va.gov/exchange/ccn/2.0}SoleProprieter" minOccurs="0"/&gt;
 *         &lt;element name="OrganizationSubpart" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SubpartLegalBusinessName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SubpartTaxId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Npi", propOrder = {

})
public class Npi {

    @XmlElement(name = "Number", required = true)
    protected String number;
    @XmlElement(name = "EntityTypeCode", required = true)
    protected String entityTypeCode;
    @XmlElement(name = "SoleProprieter")
    @XmlSchemaType(name = "string")
    protected SoleProprieter soleProprieter;
    @XmlElement(name = "OrganizationSubpart")
    protected String organizationSubpart;
    @XmlElement(name = "SubpartLegalBusinessName")
    protected String subpartLegalBusinessName;
    @XmlElement(name = "SubpartTaxId")
    protected String subpartTaxId;

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the entityTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityTypeCode() {
        return entityTypeCode;
    }

    /**
     * Sets the value of the entityTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityTypeCode(String value) {
        this.entityTypeCode = value;
    }

    /**
     * Gets the value of the soleProprieter property.
     * 
     * @return
     *     possible object is
     *     {@link SoleProprieter }
     *     
     */
    public SoleProprieter getSoleProprieter() {
        return soleProprieter;
    }

    /**
     * Sets the value of the soleProprieter property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoleProprieter }
     *     
     */
    public void setSoleProprieter(SoleProprieter value) {
        this.soleProprieter = value;
    }

    /**
     * Gets the value of the organizationSubpart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganizationSubpart() {
        return organizationSubpart;
    }

    /**
     * Sets the value of the organizationSubpart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganizationSubpart(String value) {
        this.organizationSubpart = value;
    }

    /**
     * Gets the value of the subpartLegalBusinessName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubpartLegalBusinessName() {
        return subpartLegalBusinessName;
    }

    /**
     * Sets the value of the subpartLegalBusinessName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubpartLegalBusinessName(String value) {
        this.subpartLegalBusinessName = value;
    }

    /**
     * Gets the value of the subpartTaxId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubpartTaxId() {
        return subpartTaxId;
    }

    /**
     * Sets the value of the subpartTaxId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubpartTaxId(String value) {
        this.subpartTaxId = value;
    }

}
