//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.27 at 09:37:45 PM EDT 
//


package gov.va.pie.ppms.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.va.pie.ppms.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ProviderResponse_QNAME = new QName("https://ppms.va.gov/exchange/ccn/2.0", "ProviderResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.va.pie.ppms.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Provider }
     * 
     */
    public Provider createProvider() {
        return new Provider();
    }

    /**
     * Create an instance of {@link Providers }
     * 
     */
    public Providers createProviders() {
        return new Providers();
    }

    /**
     * Create an instance of {@link ProviderResponse }
     * 
     */
    public ProviderResponse createProviderResponse() {
        return new ProviderResponse();
    }

    /**
     * Create an instance of {@link ProviderResponses }
     * 
     */
    public ProviderResponses createProviderResponses() {
        return new ProviderResponses();
    }

    /**
     * Create an instance of {@link Individual }
     * 
     */
    public Individual createIndividual() {
        return new Individual();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link Npis }
     * 
     */
    public Npis createNpis() {
        return new Npis();
    }

    /**
     * Create an instance of {@link Npi }
     * 
     */
    public Npi createNpi() {
        return new Npi();
    }

    /**
     * Create an instance of {@link Tins }
     * 
     */
    public Tins createTins() {
        return new Tins();
    }

    /**
     * Create an instance of {@link Tin }
     * 
     */
    public Tin createTin() {
        return new Tin();
    }

    /**
     * Create an instance of {@link ProviderCredentials }
     * 
     */
    public ProviderCredentials createProviderCredentials() {
        return new ProviderCredentials();
    }

    /**
     * Create an instance of {@link ProviderCredential }
     * 
     */
    public ProviderCredential createProviderCredential() {
        return new ProviderCredential();
    }

    /**
     * Create an instance of {@link OtherIdentifiers }
     * 
     */
    public OtherIdentifiers createOtherIdentifiers() {
        return new OtherIdentifiers();
    }

    /**
     * Create an instance of {@link OtherIdentifier }
     * 
     */
    public OtherIdentifier createOtherIdentifier() {
        return new OtherIdentifier();
    }

    /**
     * Create an instance of {@link Licensures }
     * 
     */
    public Licensures createLicensures() {
        return new Licensures();
    }

    /**
     * Create an instance of {@link Licensure }
     * 
     */
    public Licensure createLicensure() {
        return new Licensure();
    }

    /**
     * Create an instance of {@link ProviderServices }
     * 
     */
    public ProviderServices createProviderServices() {
        return new ProviderServices();
    }

    /**
     * Create an instance of {@link ProviderService }
     * 
     */
    public ProviderService createProviderService() {
        return new ProviderService();
    }

    /**
     * Create an instance of {@link Contacts }
     * 
     */
    public Contacts createContacts() {
        return new Contacts();
    }

    /**
     * Create an instance of {@link PersonContact }
     * 
     */
    public PersonContact createPersonContact() {
        return new PersonContact();
    }

    /**
     * Create an instance of {@link Emails }
     * 
     */
    public Emails createEmails() {
        return new Emails();
    }

    /**
     * Create an instance of {@link Email }
     * 
     */
    public Email createEmail() {
        return new Email();
    }

    /**
     * Create an instance of {@link Addresses }
     * 
     */
    public Addresses createAddresses() {
        return new Addresses();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Phones }
     * 
     */
    public Phones createPhones() {
        return new Phones();
    }

    /**
     * Create an instance of {@link Phone }
     * 
     */
    public Phone createPhone() {
        return new Phone();
    }

    /**
     * Create an instance of {@link OrganizationAuthorizedOfficials }
     * 
     */
    public OrganizationAuthorizedOfficials createOrganizationAuthorizedOfficials() {
        return new OrganizationAuthorizedOfficials();
    }

    /**
     * Create an instance of {@link OrganizationAuthorizedOfficial }
     * 
     */
    public OrganizationAuthorizedOfficial createOrganizationAuthorizedOfficial() {
        return new OrganizationAuthorizedOfficial();
    }

    /**
     * Create an instance of {@link MedicalEducations }
     * 
     */
    public MedicalEducations createMedicalEducations() {
        return new MedicalEducations();
    }

    /**
     * Create an instance of {@link MedicalEducation }
     * 
     */
    public MedicalEducation createMedicalEducation() {
        return new MedicalEducation();
    }

    /**
     * Create an instance of {@link BoardCertifications }
     * 
     */
    public BoardCertifications createBoardCertifications() {
        return new BoardCertifications();
    }

    /**
     * Create an instance of {@link BoardCertification }
     * 
     */
    public BoardCertification createBoardCertification() {
        return new BoardCertification();
    }

    /**
     * Create an instance of {@link IndividualProviderPrivileges }
     * 
     */
    public IndividualProviderPrivileges createIndividualProviderPrivileges() {
        return new IndividualProviderPrivileges();
    }

    /**
     * Create an instance of {@link IndividualProviderPrivilege }
     * 
     */
    public IndividualProviderPrivilege createIndividualProviderPrivilege() {
        return new IndividualProviderPrivilege();
    }

    /**
     * Create an instance of {@link ProviderOtherNames }
     * 
     */
    public ProviderOtherNames createProviderOtherNames() {
        return new ProviderOtherNames();
    }

    /**
     * Create an instance of {@link ProviderOtherName }
     * 
     */
    public ProviderOtherName createProviderOtherName() {
        return new ProviderOtherName();
    }

    /**
     * Create an instance of {@link DeaSchedulePrivileges }
     * 
     */
    public DeaSchedulePrivileges createDeaSchedulePrivileges() {
        return new DeaSchedulePrivileges();
    }

    /**
     * Create an instance of {@link DeaSchedulePrivilege }
     * 
     */
    public DeaSchedulePrivilege createDeaSchedulePrivilege() {
        return new DeaSchedulePrivilege();
    }

    /**
     * Create an instance of {@link OrganizationContacts }
     * 
     */
    public OrganizationContacts createOrganizationContacts() {
        return new OrganizationContacts();
    }

    /**
     * Create an instance of {@link RelatedContact }
     * 
     */
    public RelatedContact createRelatedContact() {
        return new RelatedContact();
    }

    /**
     * Create an instance of {@link Specialties }
     * 
     */
    public Specialties createSpecialties() {
        return new Specialties();
    }

    /**
     * Create an instance of {@link Taxonomy }
     * 
     */
    public Taxonomy createTaxonomy() {
        return new Taxonomy();
    }

    /**
     * Create an instance of {@link ServiceAvailabilities }
     * 
     */
    public ServiceAvailabilities createServiceAvailabilities() {
        return new ServiceAvailabilities();
    }

    /**
     * Create an instance of {@link ServiceAvailability }
     * 
     */
    public ServiceAvailability createServiceAvailability() {
        return new ServiceAvailability();
    }

    /**
     * Create an instance of {@link Locations }
     * 
     */
    public Locations createLocations() {
        return new Locations();
    }

    /**
     * Create an instance of {@link CareSite }
     * 
     */
    public CareSite createCareSite() {
        return new CareSite();
    }

    /**
     * Create an instance of {@link PlaceOfServiceCodes }
     * 
     */
    public PlaceOfServiceCodes createPlaceOfServiceCodes() {
        return new PlaceOfServiceCodes();
    }

    /**
     * Create an instance of {@link PlaceOfService }
     * 
     */
    public PlaceOfService createPlaceOfService() {
        return new PlaceOfService();
    }

    /**
     * Create an instance of {@link PreferredReferralMeans }
     * 
     */
    public PreferredReferralMeans createPreferredReferralMeans() {
        return new PreferredReferralMeans();
    }

    /**
     * Create an instance of {@link Results }
     * 
     */
    public Results createResults() {
        return new Results();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link Provider.Type }
     * 
     */
    public Provider.Type createProviderType() {
        return new Provider.Type();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProviderResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://ppms.va.gov/exchange/ccn/2.0", name = "ProviderResponse")
    public JAXBElement<ProviderResponse> createProviderResponse(ProviderResponse value) {
        return new JAXBElement<ProviderResponse>(_ProviderResponse_QNAME, ProviderResponse.class, null, value);
    }

}
