//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 03:53:36 PM EDT 
//


package gov.va.pie.ppms.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrganizationAuthorizedOfficial complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrganizationAuthorizedOfficial"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OfficialName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="OfficialCredential" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TitleOrPosition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrganizationAuthorizedOfficial", propOrder = {
    "officialName",
    "officialCredential",
    "titleOrPosition",
    "phoneNumber"
})
public class OrganizationAuthorizedOfficial {

    @XmlElement(name = "OfficialName", required = true)
    protected String officialName;
    @XmlElement(name = "OfficialCredential", required = true)
    protected String officialCredential;
    @XmlElement(name = "TitleOrPosition")
    protected String titleOrPosition;
    @XmlElement(name = "PhoneNumber")
    protected String phoneNumber;

    /**
     * Gets the value of the officialName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfficialName() {
        return officialName;
    }

    /**
     * Sets the value of the officialName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfficialName(String value) {
        this.officialName = value;
    }

    /**
     * Gets the value of the officialCredential property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfficialCredential() {
        return officialCredential;
    }

    /**
     * Sets the value of the officialCredential property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfficialCredential(String value) {
        this.officialCredential = value;
    }

    /**
     * Gets the value of the titleOrPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleOrPosition() {
        return titleOrPosition;
    }

    /**
     * Sets the value of the titleOrPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleOrPosition(String value) {
        this.titleOrPosition = value;
    }

    /**
     * Gets the value of the phoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNumber(String value) {
        this.phoneNumber = value;
    }

}
