//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 03:53:36 PM EDT 
//


package gov.va.pie.ppms.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Organization complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Organization"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ProviderName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Locations" type="{https://ppms.va.gov/exchange/ccn/2.0}Locations" minOccurs="0"/&gt;
 *         &lt;element name="ProviderServices" type="{https://ppms.va.gov/exchange/ccn/2.0}ProviderServices" minOccurs="0"/&gt;
 *         &lt;element name="AuthorizedOfficials" type="{https://ppms.va.gov/exchange/ccn/2.0}OrganizationAuthorizedOfficials" minOccurs="0"/&gt;
 *         &lt;element name="OrganizationalContacts" type="{https://ppms.va.gov/exchange/ccn/2.0}OrganizationContacts" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Organization", propOrder = {
    "providerName",
    "locations",
    "providerServices",
    "authorizedOfficials",
    "organizationalContacts"
})
public class Organization {

    @XmlElement(name = "ProviderName")
    protected String providerName;
    @XmlElement(name = "Locations")
    protected Locations locations;
    @XmlElement(name = "ProviderServices")
    protected ProviderServices providerServices;
    @XmlElement(name = "AuthorizedOfficials")
    protected OrganizationAuthorizedOfficials authorizedOfficials;
    @XmlElement(name = "OrganizationalContacts")
    protected OrganizationContacts organizationalContacts;

    /**
     * Gets the value of the providerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderName() {
        return providerName;
    }

    /**
     * Sets the value of the providerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderName(String value) {
        this.providerName = value;
    }

    /**
     * Gets the value of the locations property.
     * 
     * @return
     *     possible object is
     *     {@link Locations }
     *     
     */
    public Locations getLocations() {
        return locations;
    }

    /**
     * Sets the value of the locations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Locations }
     *     
     */
    public void setLocations(Locations value) {
        this.locations = value;
    }

    /**
     * Gets the value of the providerServices property.
     * 
     * @return
     *     possible object is
     *     {@link ProviderServices }
     *     
     */
    public ProviderServices getProviderServices() {
        return providerServices;
    }

    /**
     * Sets the value of the providerServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProviderServices }
     *     
     */
    public void setProviderServices(ProviderServices value) {
        this.providerServices = value;
    }

    /**
     * Gets the value of the authorizedOfficials property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationAuthorizedOfficials }
     *     
     */
    public OrganizationAuthorizedOfficials getAuthorizedOfficials() {
        return authorizedOfficials;
    }

    /**
     * Sets the value of the authorizedOfficials property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationAuthorizedOfficials }
     *     
     */
    public void setAuthorizedOfficials(OrganizationAuthorizedOfficials value) {
        this.authorizedOfficials = value;
    }

    /**
     * Gets the value of the organizationalContacts property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationContacts }
     *     
     */
    public OrganizationContacts getOrganizationalContacts() {
        return organizationalContacts;
    }

    /**
     * Sets the value of the organizationalContacts property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationContacts }
     *     
     */
    public void setOrganizationalContacts(OrganizationContacts value) {
        this.organizationalContacts = value;
    }

}
