//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 03:53:36 PM EDT 
//


package gov.va.pie.ppms.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OtherNameType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OtherNameType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Other"/&gt;
 *     &lt;enumeration value="Former Name"/&gt;
 *     &lt;enumeration value="Professional Name"/&gt;
 *     &lt;enumeration value="Doing Business As"/&gt;
 *     &lt;enumeration value="Former Legal Business Name"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "OtherNameType")
@XmlEnum
public enum OtherNameType {

    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("Former Name")
    FORMER_NAME("Former Name"),
    @XmlEnumValue("Professional Name")
    PROFESSIONAL_NAME("Professional Name"),
    @XmlEnumValue("Doing Business As")
    DOING_BUSINESS_AS("Doing Business As"),
    @XmlEnumValue("Former Legal Business Name")
    FORMER_LEGAL_BUSINESS_NAME("Former Legal Business Name");
    private final String value;

    OtherNameType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OtherNameType fromValue(String v) {
        for (OtherNameType c: OtherNameType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
