//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 03:53:36 PM EDT 
//


package gov.va.pie.ppms.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OtherIdentifier complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OtherIdentifier"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="IdentifierTypeCode" type="{https://ppms.va.gov/exchange/ccn/2.0}IdentifierTypeCodeList"/&gt;
 *         &lt;element name="IdentifierState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IdentifierIssuer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OtherIdentifier", propOrder = {
    "name",
    "identifierTypeCode",
    "identifierState",
    "identifierIssuer"
})
public class OtherIdentifier {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "IdentifierTypeCode", required = true)
    @XmlSchemaType(name = "string")
    protected IdentifierTypeCodeList identifierTypeCode;
    @XmlElement(name = "IdentifierState")
    protected String identifierState;
    @XmlElement(name = "IdentifierIssuer")
    protected String identifierIssuer;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the identifierTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierTypeCodeList }
     *     
     */
    public IdentifierTypeCodeList getIdentifierTypeCode() {
        return identifierTypeCode;
    }

    /**
     * Sets the value of the identifierTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierTypeCodeList }
     *     
     */
    public void setIdentifierTypeCode(IdentifierTypeCodeList value) {
        this.identifierTypeCode = value;
    }

    /**
     * Gets the value of the identifierState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifierState() {
        return identifierState;
    }

    /**
     * Sets the value of the identifierState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifierState(String value) {
        this.identifierState = value;
    }

    /**
     * Gets the value of the identifierIssuer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifierIssuer() {
        return identifierIssuer;
    }

    /**
     * Sets the value of the identifierIssuer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifierIssuer(String value) {
        this.identifierIssuer = value;
    }

}
