//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 03:53:36 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://ppms.va.gov/exchange/ccn/2.0")
package gov.va.pie.ppms.model;
