//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 03:53:36 PM EDT 
//


package gov.va.pie.ppms.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ProviderCredential complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProviderCredential"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CredentialNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CredentialType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CredentialingStatus" type="{https://ppms.va.gov/exchange/ccn/2.0}CredentialingStatus"/&gt;
 *         &lt;element name="CredentialedDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="NextCredentialingDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProviderCredential", propOrder = {
    "name",
    "credentialNumber",
    "credentialType",
    "credentialingStatus",
    "credentialedDate",
    "nextCredentialingDate",
    "description"
})
public class ProviderCredential {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "CredentialNumber", required = true)
    protected String credentialNumber;
    @XmlElement(name = "CredentialType", required = true)
    protected String credentialType;
    @XmlElement(name = "CredentialingStatus", required = true)
    @XmlSchemaType(name = "string")
    protected CredentialingStatus credentialingStatus;
    @XmlElement(name = "CredentialedDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar credentialedDate;
    @XmlElement(name = "NextCredentialingDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar nextCredentialingDate;
    @XmlElement(name = "Description")
    protected String description;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the credentialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCredentialNumber() {
        return credentialNumber;
    }

    /**
     * Sets the value of the credentialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCredentialNumber(String value) {
        this.credentialNumber = value;
    }

    /**
     * Gets the value of the credentialType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCredentialType() {
        return credentialType;
    }

    /**
     * Sets the value of the credentialType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCredentialType(String value) {
        this.credentialType = value;
    }

    /**
     * Gets the value of the credentialingStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CredentialingStatus }
     *     
     */
    public CredentialingStatus getCredentialingStatus() {
        return credentialingStatus;
    }

    /**
     * Sets the value of the credentialingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CredentialingStatus }
     *     
     */
    public void setCredentialingStatus(CredentialingStatus value) {
        this.credentialingStatus = value;
    }

    /**
     * Gets the value of the credentialedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCredentialedDate() {
        return credentialedDate;
    }

    /**
     * Sets the value of the credentialedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCredentialedDate(XMLGregorianCalendar value) {
        this.credentialedDate = value;
    }

    /**
     * Gets the value of the nextCredentialingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNextCredentialingDate() {
        return nextCredentialingDate;
    }

    /**
     * Sets the value of the nextCredentialingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNextCredentialingDate(XMLGregorianCalendar value) {
        this.nextCredentialingDate = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
