//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 03:53:36 PM EDT 
//


package gov.va.pie.ppms.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Provider complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Provider"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CorrelationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TransactionType" type="{https://ppms.va.gov/exchange/ccn/2.0}TransactionTypeList"/&gt;
 *         &lt;element name="ProviderId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Fax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Address" type="{https://ppms.va.gov/exchange/ccn/2.0}Address" minOccurs="0"/&gt;
 *         &lt;element name="HealthProviderType" type="{https://ppms.va.gov/exchange/ccn/2.0}HealthProviderType" minOccurs="0"/&gt;
 *         &lt;element name="InternalType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DateOfBirth" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="PrimaryDM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SecondaryDM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EmrSystem" type="{https://ppms.va.gov/exchange/ccn/2.0}EmrSystemType" minOccurs="0"/&gt;
 *         &lt;element name="EmrSystemOther" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Npis" type="{https://ppms.va.gov/exchange/ccn/2.0}Npis"/&gt;
 *         &lt;element name="Tins" type="{https://ppms.va.gov/exchange/ccn/2.0}Tins" minOccurs="0"/&gt;
 *         &lt;element name="StationNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Licensures" type="{https://ppms.va.gov/exchange/ccn/2.0}Licensures" minOccurs="0"/&gt;
 *         &lt;element name="Specialties" type="{https://ppms.va.gov/exchange/ccn/2.0}Specialties" minOccurs="0"/&gt;
 *         &lt;element name="OtherIdentifiers" type="{https://ppms.va.gov/exchange/ccn/2.0}OtherIdentifiers" minOccurs="0"/&gt;
 *         &lt;element name="PreferredReferralMeans" type="{https://ppms.va.gov/exchange/ccn/2.0}PreferredReferralMeans" minOccurs="0"/&gt;
 *         &lt;element name="Type" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="Individual" type="{https://ppms.va.gov/exchange/ccn/2.0}Individual"/&gt;
 *                   &lt;element name="Organization" type="{https://ppms.va.gov/exchange/ccn/2.0}Organization"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Provider", propOrder = {
    "correlationId",
    "transactionType",
    "providerId",
    "email",
    "phone",
    "fax",
    "address",
    "healthProviderType",
    "internalType",
    "dateOfBirth",
    "primaryDM",
    "secondaryDM",
    "emrSystem",
    "emrSystemOther",
    "npis",
    "tins",
    "stationNumber",
    "licensures",
    "specialties",
    "otherIdentifiers",
    "preferredReferralMeans",
    "type"
})
public class Provider {

    @XmlElement(name = "CorrelationId")
    protected String correlationId;
    @XmlElement(name = "TransactionType", required = true)
    @XmlSchemaType(name = "string")
    protected TransactionTypeList transactionType;
    @XmlElement(name = "ProviderId", required = true)
    protected String providerId;
    @XmlElement(name = "Email")
    protected String email;
    @XmlElement(name = "Phone")
    protected String phone;
    @XmlElement(name = "Fax")
    protected String fax;
    @XmlElement(name = "Address")
    protected Address address;
    @XmlElement(name = "HealthProviderType")
    @XmlSchemaType(name = "string")
    protected HealthProviderType healthProviderType;
    @XmlElement(name = "InternalType")
    protected String internalType;
    @XmlElement(name = "DateOfBirth")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfBirth;
    @XmlElement(name = "PrimaryDM")
    protected String primaryDM;
    @XmlElement(name = "SecondaryDM")
    protected String secondaryDM;
    @XmlElement(name = "EmrSystem")
    @XmlSchemaType(name = "string")
    protected EmrSystemType emrSystem;
    @XmlElement(name = "EmrSystemOther")
    protected String emrSystemOther;
    @XmlElement(name = "Npis", required = true)
    protected Npis npis;
    @XmlElement(name = "Tins")
    protected Tins tins;
    @XmlElement(name = "StationNumber")
    protected String stationNumber;
    @XmlElement(name = "Licensures")
    protected Licensures licensures;
    @XmlElement(name = "Specialties")
    protected Specialties specialties;
    @XmlElement(name = "OtherIdentifiers")
    protected OtherIdentifiers otherIdentifiers;
    @XmlElement(name = "PreferredReferralMeans")
    protected PreferredReferralMeans preferredReferralMeans;
    @XmlElement(name = "Type")
    protected Provider.Type type;

    /**
     * Gets the value of the correlationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrelationId() {
        return correlationId;
    }

    /**
     * Sets the value of the correlationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrelationId(String value) {
        this.correlationId = value;
    }

    /**
     * Gets the value of the transactionType property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionTypeList }
     *     
     */
    public TransactionTypeList getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionTypeList }
     *     
     */
    public void setTransactionType(TransactionTypeList value) {
        this.transactionType = value;
    }

    /**
     * Gets the value of the providerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderId() {
        return providerId;
    }

    /**
     * Sets the value of the providerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderId(String value) {
        this.providerId = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFax(String value) {
        this.fax = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(Address value) {
        this.address = value;
    }

    /**
     * Gets the value of the healthProviderType property.
     * 
     * @return
     *     possible object is
     *     {@link HealthProviderType }
     *     
     */
    public HealthProviderType getHealthProviderType() {
        return healthProviderType;
    }

    /**
     * Sets the value of the healthProviderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link HealthProviderType }
     *     
     */
    public void setHealthProviderType(HealthProviderType value) {
        this.healthProviderType = value;
    }

    /**
     * Gets the value of the internalType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalType() {
        return internalType;
    }

    /**
     * Sets the value of the internalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalType(String value) {
        this.internalType = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfBirth(XMLGregorianCalendar value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the primaryDM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryDM() {
        return primaryDM;
    }

    /**
     * Sets the value of the primaryDM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryDM(String value) {
        this.primaryDM = value;
    }

    /**
     * Gets the value of the secondaryDM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondaryDM() {
        return secondaryDM;
    }

    /**
     * Sets the value of the secondaryDM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondaryDM(String value) {
        this.secondaryDM = value;
    }

    /**
     * Gets the value of the emrSystem property.
     * 
     * @return
     *     possible object is
     *     {@link EmrSystemType }
     *     
     */
    public EmrSystemType getEmrSystem() {
        return emrSystem;
    }

    /**
     * Sets the value of the emrSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmrSystemType }
     *     
     */
    public void setEmrSystem(EmrSystemType value) {
        this.emrSystem = value;
    }

    /**
     * Gets the value of the emrSystemOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmrSystemOther() {
        return emrSystemOther;
    }

    /**
     * Sets the value of the emrSystemOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmrSystemOther(String value) {
        this.emrSystemOther = value;
    }

    /**
     * Gets the value of the npis property.
     * 
     * @return
     *     possible object is
     *     {@link Npis }
     *     
     */
    public Npis getNpis() {
        return npis;
    }

    /**
     * Sets the value of the npis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Npis }
     *     
     */
    public void setNpis(Npis value) {
        this.npis = value;
    }

    /**
     * Gets the value of the tins property.
     * 
     * @return
     *     possible object is
     *     {@link Tins }
     *     
     */
    public Tins getTins() {
        return tins;
    }

    /**
     * Sets the value of the tins property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tins }
     *     
     */
    public void setTins(Tins value) {
        this.tins = value;
    }

    /**
     * Gets the value of the stationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStationNumber() {
        return stationNumber;
    }

    /**
     * Sets the value of the stationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStationNumber(String value) {
        this.stationNumber = value;
    }

    /**
     * Gets the value of the licensures property.
     * 
     * @return
     *     possible object is
     *     {@link Licensures }
     *     
     */
    public Licensures getLicensures() {
        return licensures;
    }

    /**
     * Sets the value of the licensures property.
     * 
     * @param value
     *     allowed object is
     *     {@link Licensures }
     *     
     */
    public void setLicensures(Licensures value) {
        this.licensures = value;
    }

    /**
     * Gets the value of the specialties property.
     * 
     * @return
     *     possible object is
     *     {@link Specialties }
     *     
     */
    public Specialties getSpecialties() {
        return specialties;
    }

    /**
     * Sets the value of the specialties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Specialties }
     *     
     */
    public void setSpecialties(Specialties value) {
        this.specialties = value;
    }

    /**
     * Gets the value of the otherIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link OtherIdentifiers }
     *     
     */
    public OtherIdentifiers getOtherIdentifiers() {
        return otherIdentifiers;
    }

    /**
     * Sets the value of the otherIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherIdentifiers }
     *     
     */
    public void setOtherIdentifiers(OtherIdentifiers value) {
        this.otherIdentifiers = value;
    }

    /**
     * Gets the value of the preferredReferralMeans property.
     * 
     * @return
     *     possible object is
     *     {@link PreferredReferralMeans }
     *     
     */
    public PreferredReferralMeans getPreferredReferralMeans() {
        return preferredReferralMeans;
    }

    /**
     * Sets the value of the preferredReferralMeans property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreferredReferralMeans }
     *     
     */
    public void setPreferredReferralMeans(PreferredReferralMeans value) {
        this.preferredReferralMeans = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link Provider.Type }
     *     
     */
    public Provider.Type getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link Provider.Type }
     *     
     */
    public void setType(Provider.Type value) {
        this.type = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="Individual" type="{https://ppms.va.gov/exchange/ccn/2.0}Individual"/&gt;
     *         &lt;element name="Organization" type="{https://ppms.va.gov/exchange/ccn/2.0}Organization"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "individual",
        "organization"
    })
    public static class Type {

        @XmlElement(name = "Individual")
        protected Individual individual;
        @XmlElement(name = "Organization")
        protected Organization organization;

        /**
         * Gets the value of the individual property.
         * 
         * @return
         *     possible object is
         *     {@link Individual }
         *     
         */
        public Individual getIndividual() {
            return individual;
        }

        /**
         * Sets the value of the individual property.
         * 
         * @param value
         *     allowed object is
         *     {@link Individual }
         *     
         */
        public void setIndividual(Individual value) {
            this.individual = value;
        }

        /**
         * Gets the value of the organization property.
         * 
         * @return
         *     possible object is
         *     {@link Organization }
         *     
         */
        public Organization getOrganization() {
            return organization;
        }

        /**
         * Sets the value of the organization property.
         * 
         * @param value
         *     allowed object is
         *     {@link Organization }
         *     
         */
        public void setOrganization(Organization value) {
            this.organization = value;
        }

    }

}
