//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 03:53:36 PM EDT 
//


package gov.va.pie.ppms.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProviderService complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProviderService"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="CorrelationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CodedSpecialty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Relationship" type="{https://ppms.va.gov/exchange/ccn/2.0}RelationshipType" minOccurs="0"/&gt;
 *         &lt;element name="StationNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Location" type="{https://ppms.va.gov/exchange/ccn/2.0}CareSite" minOccurs="0"/&gt;
 *         &lt;element name="HighPerformingProvider" type="{https://ppms.va.gov/exchange/ccn/2.0}YesNoType" minOccurs="0"/&gt;
 *         &lt;element name="OrganizationNpi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ServiceAvailability" type="{https://ppms.va.gov/exchange/ccn/2.0}ServiceAvailabilities" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProviderService", propOrder = {

})
public class ProviderService {

    @XmlElement(name = "CorrelationId")
    protected String correlationId;
    @XmlElement(name = "CodedSpecialty")
    protected String codedSpecialty;
    @XmlElement(name = "Relationship")
    @XmlSchemaType(name = "string")
    protected RelationshipType relationship;
    @XmlElement(name = "StationNumber")
    protected String stationNumber;
    @XmlElement(name = "Location")
    protected CareSite location;
    @XmlElement(name = "HighPerformingProvider")
    @XmlSchemaType(name = "string")
    protected YesNoType highPerformingProvider;
    @XmlElement(name = "OrganizationNpi")
    protected String organizationNpi;
    @XmlElement(name = "ServiceAvailability")
    protected ServiceAvailabilities serviceAvailability;

    /**
     * Gets the value of the correlationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrelationId() {
        return correlationId;
    }

    /**
     * Sets the value of the correlationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrelationId(String value) {
        this.correlationId = value;
    }

    /**
     * Gets the value of the codedSpecialty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodedSpecialty() {
        return codedSpecialty;
    }

    /**
     * Sets the value of the codedSpecialty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodedSpecialty(String value) {
        this.codedSpecialty = value;
    }

    /**
     * Gets the value of the relationship property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipType }
     *     
     */
    public RelationshipType getRelationship() {
        return relationship;
    }

    /**
     * Sets the value of the relationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipType }
     *     
     */
    public void setRelationship(RelationshipType value) {
        this.relationship = value;
    }

    /**
     * Gets the value of the stationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStationNumber() {
        return stationNumber;
    }

    /**
     * Sets the value of the stationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStationNumber(String value) {
        this.stationNumber = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link CareSite }
     *     
     */
    public CareSite getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link CareSite }
     *     
     */
    public void setLocation(CareSite value) {
        this.location = value;
    }

    /**
     * Gets the value of the highPerformingProvider property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getHighPerformingProvider() {
        return highPerformingProvider;
    }

    /**
     * Sets the value of the highPerformingProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setHighPerformingProvider(YesNoType value) {
        this.highPerformingProvider = value;
    }

    /**
     * Gets the value of the organizationNpi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganizationNpi() {
        return organizationNpi;
    }

    /**
     * Sets the value of the organizationNpi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganizationNpi(String value) {
        this.organizationNpi = value;
    }

    /**
     * Gets the value of the serviceAvailability property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceAvailabilities }
     *     
     */
    public ServiceAvailabilities getServiceAvailability() {
        return serviceAvailability;
    }

    /**
     * Sets the value of the serviceAvailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceAvailabilities }
     *     
     */
    public void setServiceAvailability(ServiceAvailabilities value) {
        this.serviceAvailability = value;
    }

}
