//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 03:53:36 PM EDT 
//


package gov.va.pie.ppms.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProviderOtherName complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProviderOtherName"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="OtherNameType" type="{https://ppms.va.gov/exchange/ccn/2.0}OtherNameType" minOccurs="0"/&gt;
 *         &lt;element name="OtherCredential" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProviderOtherName", propOrder = {
    "name",
    "otherNameType",
    "otherCredential"
})
public class ProviderOtherName {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "OtherNameType")
    @XmlSchemaType(name = "string")
    protected OtherNameType otherNameType;
    @XmlElement(name = "OtherCredential")
    protected String otherCredential;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the otherNameType property.
     * 
     * @return
     *     possible object is
     *     {@link OtherNameType }
     *     
     */
    public OtherNameType getOtherNameType() {
        return otherNameType;
    }

    /**
     * Sets the value of the otherNameType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherNameType }
     *     
     */
    public void setOtherNameType(OtherNameType value) {
        this.otherNameType = value;
    }

    /**
     * Gets the value of the otherCredential property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherCredential() {
        return otherCredential;
    }

    /**
     * Sets the value of the otherCredential property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherCredential(String value) {
        this.otherCredential = value;
    }

}
