//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 03:53:36 PM EDT 
//


package gov.va.pie.ppms.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Taxonomy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Taxonomy"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CodedSpecialty" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="IsPrimaryTaxonomy" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Taxonomy", propOrder = {
    "codedSpecialty",
    "isPrimaryTaxonomy"
})
public class Taxonomy {

    @XmlElement(name = "CodedSpecialty", required = true)
    protected String codedSpecialty;
    @XmlElement(name = "IsPrimaryTaxonomy")
    protected boolean isPrimaryTaxonomy;

    /**
     * Gets the value of the codedSpecialty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodedSpecialty() {
        return codedSpecialty;
    }

    /**
     * Sets the value of the codedSpecialty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodedSpecialty(String value) {
        this.codedSpecialty = value;
    }

    /**
     * Gets the value of the isPrimaryTaxonomy property.
     * 
     */
    public boolean isIsPrimaryTaxonomy() {
        return isPrimaryTaxonomy;
    }

    /**
     * Sets the value of the isPrimaryTaxonomy property.
     * 
     */
    public void setIsPrimaryTaxonomy(boolean value) {
        this.isPrimaryTaxonomy = value;
    }

}
