//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 03:53:36 PM EDT 
//


package gov.va.pie.ppms.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransactionTypeList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TransactionTypeList"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Update"/&gt;
 *     &lt;enumeration value="Deactivate Provider"/&gt;
 *     &lt;enumeration value="Deactivate Relationship"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TransactionTypeList")
@XmlEnum
public enum TransactionTypeList {

    @XmlEnumValue("Update")
    UPDATE("Update"),
    @XmlEnumValue("Deactivate Provider")
    DEACTIVATE_PROVIDER("Deactivate Provider"),
    @XmlEnumValue("Deactivate Relationship")
    DEACTIVATE_RELATIONSHIP("Deactivate Relationship");
    private final String value;

    TransactionTypeList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TransactionTypeList fromValue(String v) {
        for (TransactionTypeList c: TransactionTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
