//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.17 at 01:15:37 PM EDT 
//


package gov.va.pie.cdw.vast.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Facility complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Facility">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CorrelationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StationNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StationName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Facility" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FacilityType" type="{https://ppms.va.gov/exchange/ccn/2.0}FacilityType"/>
 *         &lt;element name="Visn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Address" type="{https://ppms.va.gov/exchange/ccn/2.0}Address" minOccurs="0"/>
 *         &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Fax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Rurality" type="{https://ppms.va.gov/exchange/ccn/2.0}RuralityType" minOccurs="0"/>
 *         &lt;element name="ParentStationNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Facility", propOrder = {
    "stationNumber",
    "stationName",
    "facility",
    "facilityType",
    "visn",
    "address",
    "phone",
    "fax",
    "rurality",
    "parentStationNumber",
    "latitude",
    "longitude"
})
public class Facility {

    @XmlElement(name = "StationNumber", required = true)
    protected String stationNumber;
    @XmlElement(name = "StationName", required = true)
    protected String stationName;
    @XmlElement(name = "Facility", required = true)
    protected String facility;
    @XmlElement(name = "FacilityType", required = true)
    @XmlSchemaType(name = "string")
    protected FacilityType facilityType;
    @XmlElement(name = "Visn", required = true)
    protected String visn;
    @XmlElement(name = "Address", required = true)
    protected Address address;
    @XmlElement(name = "Phone")
    protected String phone;
    @XmlElement(name = "Fax")
    protected String fax;
    @XmlElement(name = "Rurality")
    @XmlSchemaType(name = "string")
    protected RuralityType rurality;
    @XmlElement(name = "ParentStationNumber")
    protected String parentStationNumber;
    @XmlElement(name = "Latitude")
    protected float latitude;
    @XmlElement(name = "Longitude")
    protected float longitude;


    /**
     * Gets the value of the stationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStationNumber() {
        return stationNumber;
    }

    /**
     * Sets the value of the stationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStationNumber(String value) {
        this.stationNumber = value;
    }

    /**
     * Gets the value of the stationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * Sets the value of the stationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStationName(String value) {
        this.stationName = value;
    }

    /**
     * Gets the value of the facility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacility() {
        return facility;
    }

    /**
     * Sets the value of the facility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacility(String value) {
        this.facility = value;
    }

    /**
     * Gets the value of the facilityType property.
     * 
     * @return
     *     possible object is
     *     {@link FacilityType }
     *     
     */
    public FacilityType getFacilityType() {
        return facilityType;
    }

    /**
     * Sets the value of the facilityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacilityType }
     *     
     */
    public void setFacilityType(FacilityType value) {
        this.facilityType = value;
    }

    /**
     * Gets the value of the visn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisn() {
        return visn;
    }

    /**
     * Sets the value of the visn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisn(String value) {
        this.visn = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(Address value) {
        this.address = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFax(String value) {
        this.fax = value;
    }

    /**
     * Gets the value of the rurality property.
     * 
     * @return
     *     possible object is
     *     {@link RuralityType }
     *     
     */
    public RuralityType getRurality() {
        return rurality;
    }

    /**
     * Sets the value of the rurality property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuralityType }
     *     
     */
    public void setRurality(RuralityType value) {
        this.rurality = value;
    }

    /**
     * Gets the value of the parentStationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentStationNumber() {
        return parentStationNumber;
    }

    /**
     * Sets the value of the parentStationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentStationNumber(String value) {
        this.parentStationNumber = value;
    }


    public float getLatitude() {
        return this.latitude;
    }

    public void setLatitude(float latitude) {
        this.latitude = latitude;
    }

    public float getLongitude() {
        return this.longitude;
    }

    public void setLongitude(float longitude) {
        this.longitude = longitude;
    }

}
