//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.17 at 01:15:37 PM EDT 
//


package gov.va.pie.cdw.vast.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FacilityType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FacilityType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="VAMC"/>
 *     &lt;enumeration value="PC CBOC"/>
 *     &lt;enumeration value="OOS"/>
 *     &lt;enumeration value="MS CBOC"/>
 *     &lt;enumeration value="HCC"/>
 *     &lt;enumeration value="CLC"/>
 *     &lt;enumeration value="MH RRTP/DRRTP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FacilityType")
@XmlEnum
public enum FacilityType {

    VAMC("VAMC"),
    @XmlEnumValue("PC CBOC")
    PC_CBOC("PC CBOC"),
    OOS("OOS"),
    @XmlEnumValue("MS CBOC")
    MS_CBOC("MS CBOC"),
    HCC("HCC"),
    CLC("CLC"),
    @XmlEnumValue("MH RRTP/DRRTP")
    MH_RRTP_DRRTP("MH RRTP/DRRTP");
    private final String value;

    FacilityType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FacilityType fromValue(String v) {
        for (FacilityType c: FacilityType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
