//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.17 at 01:15:37 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://ppms.va.gov/facility/v1")
package gov.va.pie.cdw.vast.model;