BEGIN
EXECUTE IMMEDIATE 'CREATE BIGFILE TABLESPACE HADB_DATA DATAFILE ''hadb.dat'' SIZE 10M AUTOEXTEND ON';

EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE = -955 THEN
        NULL; -- suppresses ORA-00955 exception (name already being used by an existing object)
      ELSIF SQLCODE = -1543 THEN
        NULL; -- suppresses ORA-01543 exception (tablespace %s already exists)
      ELSE
         RAISE;
      END IF;
END;
/
CREATE USER HADB IDENTIFIED BY "Agilexadmin99$" DEFAULT TABLESPACE HADB_DATA;
GRANT CONNECT, RESOURCE, DBA to HADB;
GRANT CREATE SESSION GRANT ANY PRIVILEGE TO HADB;
GRANT UNLIMITED TABLESPACE TO HADB;

--------------------------------------------------------
--  DDL for Table ANNIEJMSSTOREWLSTORE
--------------------------------------------------------

  CREATE TABLE "HADB"."ANNIEJMSSTOREWLSTORE" 
   (	"ID" NUMBER(*,0), 
	"TYPE" NUMBER(*,0), 
	"HANDLE" NUMBER(*,0), 
	"RECORD" LONG RAW
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table APPOINTMENT_METRICS
--------------------------------------------------------

  CREATE TABLE "HADB"."APPOINTMENT_METRICS" 
   (	"NAME" VARCHAR2(100 BYTE), 
	"VALUE" NUMBER(9,0) DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table APPOINTMENT_REQUEST
--------------------------------------------------------

  CREATE TABLE "HADB"."APPOINTMENT_REQUEST" 
   (	"APPOINTMENT_REQUEST_ID" VARCHAR2(32 BYTE), 
	"PATIENT_ID" VARCHAR2(255 BYTE), 
	"LAST_UPDATED_DATE" TIMESTAMP (6), 
	"CREATED_DATE" TIMESTAMP (6), 
	"DELETED_DATE" TIMESTAMP (6), 
	"ACTIVE" NUMBER(1,0), 
	"SECOND_REQUEST" NUMBER(1,0), 
	"APPOINTMENT_DATE" VARCHAR2(50 BYTE), 
	"APPOINTMENT_TIME" VARCHAR2(50 BYTE), 
	"OPTION_DATE_1" VARCHAR2(50 BYTE), 
	"OPTION_TIME_1" VARCHAR2(50 BYTE), 
	"OPTION_DATE_2" VARCHAR2(50 BYTE), 
	"OPTION_TIME_2" VARCHAR2(50 BYTE), 
	"OPTION_DATE_3" VARCHAR2(50 BYTE), 
	"OPTION_TIME_3" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(255 BYTE), 
	"APPOINTMENT_TYPE" VARCHAR2(255 BYTE), 
	"FACILITY_CODE" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"PHONE_NUMBER" VARCHAR2(255 BYTE), 
	"TEXT_MESSAGING_ALLOWED" NUMBER(1,0), 
	"TEXT_MESSAGING_PHONE_NUMBER" VARCHAR2(255 BYTE), 
	"PURPOSE_OF_VISIT" VARCHAR2(255 BYTE), 
	"OTHER_PURPOSE_OF_VISIT" VARCHAR2(100 BYTE), 
	"VISIT_TYPE" VARCHAR2(40 BYTE), 
	"PROVIDER_ID" VARCHAR2(255 BYTE), 
	"PROVIDER_NAME" VARCHAR2(255 BYTE), 
	"PROVIDER_PERSON_CLASS" VARCHAR2(255 BYTE), 
	"PROVIDER_OPTION" VARCHAR2(100 BYTE), 
	"SECOND_REQUEST_SUBMITTED" NUMBER(1,0), 
	"PARENT_REQUEST_ID" VARCHAR2(32 BYTE), 
	"HAS_VETERAN_NEW_MESSAGE" NUMBER(1,0) DEFAULT 0, 
	"HAS_PROVIDER_NEW_MESSAGE" NUMBER(1,0) DEFAULT 0, 
	"PROVIDER_SEEN_APPT_REQ" NUMBER(1,0) DEFAULT 0, 
	"REQUESTED_PHONE_CALL" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table APPOINTMENT_REQUEST_MESSAGE
--------------------------------------------------------

  CREATE TABLE "HADB"."APPOINTMENT_REQUEST_MESSAGE" 
   (	"ID" VARCHAR2(32 BYTE), 
	"APPOINTMENT_REQUEST_ID" VARCHAR2(32 BYTE), 
	"SENDER_ID" VARCHAR2(255 BYTE), 
	"MESSAGE_TEXT" VARCHAR2(255 BYTE), 
	"MESSAGE_DATE_TIME" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table APPT_REQ_INPROCESS
--------------------------------------------------------

  CREATE TABLE "HADB"."APPT_REQ_INPROCESS" 
   (	"APPT_REQ_ID" VARCHAR2(32 BYTE), 
	"USER_ID" VARCHAR2(255 BYTE), 
	"FIRST_NAME" VARCHAR2(255 BYTE), 
	"LAST_NAME" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table AR_DETAIL_CODE
--------------------------------------------------------

  CREATE TABLE "HADB"."AR_DETAIL_CODE" 
   (	"AR_DETAIL_CODE_ID" VARCHAR2(32 BYTE), 
	"DETAIL_CODE_ID" VARCHAR2(32 BYTE), 
	"APPOINTMENT_REQUEST_ID" VARCHAR2(32 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"USER_ID" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table ASSESSMENTS
--------------------------------------------------------

  CREATE TABLE "HADB"."ASSESSMENTS" 
   (	"ID" VARCHAR2(32 BYTE), 
	"UNIQUE_TITLE" VARCHAR2(255 BYTE), 
	"VERSION" VARCHAR2(255 BYTE), 
	"AUTHENTICATION_STRATEGY" VARCHAR2(255 BYTE), 
	"IN_HEALTH_ASSESSMENT" NUMBER(1,0) DEFAULT 0, 
	"NOTES" VARCHAR2(4000 BYTE), 
	"SCORING_ALGORITHM" VARCHAR2(255 BYTE), 
	"PUBLISHED" NUMBER(1,0) DEFAULT 0, 
	"WAITING_PERIOD" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table ASSESSMENT_QUESTIONS
--------------------------------------------------------

  CREATE TABLE "HADB"."ASSESSMENT_QUESTIONS" 
   (	"ID" VARCHAR2(32 BYTE), 
	"ASSESSMENT_ID" RAW(16), 
	"QUESTION_NUMBER" NUMBER(*,0), 
	"TYPE" VARCHAR2(255 BYTE), 
	"PROMPT" VARCHAR2(255 BYTE), 
	"QUESTION_CHOICES" CLOB, 
	"PROPERTIES" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" 
 LOB ("QUESTION_CHOICES") STORE AS BASICFILE (
  TABLESPACE "HADB_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("PROPERTIES") STORE AS BASICFILE (
  TABLESPACE "HADB_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
--------------------------------------------------------
--  DDL for Table ASSESSMENT_RESULT
--------------------------------------------------------

  CREATE TABLE "HADB"."ASSESSMENT_RESULT" 
   (	"ASSESSMENT_RESULT_ID" VARCHAR2(32 BYTE), 
	"UNIQUE_TITLE" VARCHAR2(255 BYTE), 
	"VERSION" VARCHAR2(255 BYTE), 
	"AUTHENTICATION_STRATEGY" VARCHAR2(255 BYTE), 
	"PATIENT_ID" VARCHAR2(255 BYTE), 
	"NOTES" CLOB, 
	"DATE_TAKEN" TIMESTAMP (6), 
	"SCORE" NUMBER(11,0), 
	"RESPONSES" CLOB, 
	"IN_PROGRESS" NUMBER(1,0), 
	"ASSESSMENT_ID" VARCHAR2(255 BYTE), 
	"SCORING_ALGORITHM" VARCHAR2(255 BYTE), 
	"WAITING_PERIOD" NUMBER(11,0), 
	"REPORT" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" 
 LOB ("NOTES") STORE AS BASICFILE (
  TABLESPACE "HADB_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("RESPONSES") STORE AS BASICFILE (
  TABLESPACE "HADB_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("REPORT") STORE AS BASICFILE (
  TABLESPACE "HADB_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
--------------------------------------------------------
--  DDL for Table AUDIT_LOG
--------------------------------------------------------

  CREATE TABLE "HADB"."AUDIT_LOG" 
   (	"AUDIT_ID" VARCHAR2(32 BYTE), 
	"USER_ID" VARCHAR2(255 BYTE), 
	"AUDIT_TYPE" VARCHAR2(255 BYTE), 
	"AUDIT_SUBTYPE" VARCHAR2(255 BYTE), 
	"AUDIT_DATE" TIMESTAMP (6), 
	"DETAILS" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" 
 LOB ("DETAILS") STORE AS BASICFILE (
  TABLESPACE "HADB_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
--------------------------------------------------------
--  DDL for Table BEST_TIME_TO_CALL
--------------------------------------------------------

  CREATE TABLE "HADB"."BEST_TIME_TO_CALL" 
   (	"APPOINTMENT_REQUEST_ID" VARCHAR2(32 BYTE), 
	"BEST_TIME" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table CALENDAR_EVENTS
--------------------------------------------------------

  CREATE TABLE "HADB"."CALENDAR_EVENTS" 
   (	"ID" VARCHAR2(32 BYTE), 
	"PATIENT_ID" VARCHAR2(255 BYTE), 
	"TITLE" VARCHAR2(255 BYTE), 
	"NOTES" CLOB, 
	"START_DATE" TIMESTAMP (6), 
	"DURATION" NUMBER(*,0), 
	"ALERT_DURATION" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" 
 LOB ("NOTES") STORE AS BASICFILE (
  TABLESPACE "HADB_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
--------------------------------------------------------
--  DDL for Table COMMUNICATIONS
--------------------------------------------------------

  CREATE TABLE "HADB"."COMMUNICATIONS" 
   (	"ID" VARCHAR2(32 BYTE), 
	"PATIENT_ID" VARCHAR2(255 BYTE), 
	"LOG_TIME" DATE, 
	"CONTACT" VARCHAR2(255 BYTE), 
	"CONTACT_TYPE" VARCHAR2(255 BYTE), 
	"SUBJECT" VARCHAR2(255 BYTE), 
	"NOTE" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" 
 LOB ("NOTE") STORE AS BASICFILE (
  TABLESPACE "HADB_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
--------------------------------------------------------
--  DDL for Table DAILY_EVENT
--------------------------------------------------------

  CREATE TABLE "HADB"."DAILY_EVENT" 
   (	"ID" VARCHAR2(32 BYTE), 
	"PATIENT_ID" VARCHAR2(255 BYTE), 
	"TITLE" VARCHAR2(255 BYTE), 
	"ENTRY_DATE" TIMESTAMP (6), 
	"NOTE" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" 
 LOB ("NOTE") STORE AS BASICFILE (
  TABLESPACE "HADB_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
--------------------------------------------------------
--  DDL for Table DATABASECHANGELOG
--------------------------------------------------------

  CREATE TABLE "HADB"."DATABASECHANGELOG" 
   (	"ID" VARCHAR2(63 BYTE), 
	"AUTHOR" VARCHAR2(63 BYTE), 
	"FILENAME" VARCHAR2(200 BYTE), 
	"DATEEXECUTED" TIMESTAMP (6), 
	"ORDEREXECUTED" NUMBER(*,0), 
	"EXECTYPE" VARCHAR2(10 BYTE), 
	"MD5SUM" VARCHAR2(35 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"COMMENTS" VARCHAR2(255 BYTE), 
	"TAG" VARCHAR2(255 BYTE), 
	"LIQUIBASE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table DATABASECHANGELOGLOCK
--------------------------------------------------------

  CREATE TABLE "HADB"."DATABASECHANGELOGLOCK" 
   (	"ID" NUMBER(*,0), 
	"LOCKED" NUMBER(1,0), 
	"LOCKGRANTED" TIMESTAMP (6), 
	"LOCKEDBY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table DETAIL_CODE
--------------------------------------------------------

  CREATE TABLE "HADB"."DETAIL_CODE" 
   (	"DETAIL_CODE_ID" VARCHAR2(32 BYTE), 
	"PROVIDER_MESSAGE" VARCHAR2(2000 BYTE), 
	"VETERAN_MESSAGE" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table DEVICE_REGISTRATION
--------------------------------------------------------

  CREATE TABLE "HADB"."DEVICE_REGISTRATION" 
   (	"DEVICE_REGISTRATION_ID" VARCHAR2(32 BYTE), 
	"USER_ID" VARCHAR2(255 BYTE), 
	"REGISTERED_DATE" TIMESTAMP (6), 
	"DEVICE_TOKEN" VARCHAR2(100 BYTE), 
	"FIRST_NAME" VARCHAR2(255 BYTE), 
	"LAST_NAME" VARCHAR2(255 BYTE), 
	"OPTED_IN_FLAG" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table DIET
--------------------------------------------------------

  CREATE TABLE "HADB"."DIET" 
   (	"ID" VARCHAR2(32 BYTE), 
	"PATIENT_ID" VARCHAR2(255 BYTE), 
	"MEAL_TYPE" VARCHAR2(50 BYTE), 
	"CALORIES" VARCHAR2(20 BYTE), 
	"FAT" VARCHAR2(20 BYTE), 
	"CARBS" VARCHAR2(20 BYTE), 
	"PROTEIN" VARCHAR2(20 BYTE), 
	"ENTRY_DATE" TIMESTAMP (6), 
	"NOTE" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" 
 LOB ("NOTE") STORE AS BASICFILE (
  TABLESPACE "HADB_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
--------------------------------------------------------
--  DDL for Table DOCUMENTS
--------------------------------------------------------

  CREATE TABLE "HADB"."DOCUMENTS" 
   (	"ID" VARCHAR2(32 BYTE), 
	"ENTRY_ID" VARCHAR2(32 BYTE), 
	"PATIENT_ID" VARCHAR2(255 BYTE), 
	"TITLE" VARCHAR2(255 BYTE), 
	"CLASS_CODE" VARCHAR2(255 BYTE), 
	"MIME_TYPE" VARCHAR2(255 BYTE), 
	"URI" VARCHAR2(500 BYTE), 
	"DOCUMENT" BLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" 
 LOB ("DOCUMENT") STORE AS BASICFILE (
  TABLESPACE "HADB_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
--------------------------------------------------------
--  DDL for Table ENTRIES
--------------------------------------------------------

  CREATE TABLE "HADB"."ENTRIES" 
   (	"ENTRY_ID" VARCHAR2(32 BYTE), 
	"DATE_COMPLETED" TIMESTAMP (6), 
	"COMPLETED" NUMBER(1,0), 
	"PATIENT_ID" VARCHAR2(255 BYTE), 
	"DATE_CREATED" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table EXERCISE
--------------------------------------------------------

  CREATE TABLE "HADB"."EXERCISE" 
   (	"ID" VARCHAR2(32 BYTE), 
	"PATIENT_ID" VARCHAR2(255 BYTE), 
	"DURATION" NUMBER(*,0), 
	"DISTANCE" FLOAT(24), 
	"INTENSITY" VARCHAR2(255 BYTE), 
	"ACTIVITY" VARCHAR2(255 BYTE), 
	"ACTIVITY_DATE" TIMESTAMP (6), 
	"NOTE" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" 
 LOB ("NOTE") STORE AS BASICFILE (
  TABLESPACE "HADB_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
--------------------------------------------------------
--  DDL for Table FACILITY
--------------------------------------------------------

  CREATE TABLE "HADB"."FACILITY" 
   (	"NAME" VARCHAR2(100 BYTE), 
	"TYPE" VARCHAR2(100 BYTE), 
	"FACILITY_CODE" VARCHAR2(100 BYTE), 
	"STATE" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"PARENT_SITE_CODE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table HEALTH_ADVOCATE_FORM
--------------------------------------------------------

  CREATE TABLE "HADB"."HEALTH_ADVOCATE_FORM" 
   (	"HEALTH_ADVOCATE_REQUEST_ID" VARCHAR2(32 BYTE), 
	"FORM_DATA" BLOB, 
	"ID" VARCHAR2(32 BYTE), 
	"PATIENT_ID" VARCHAR2(255 BYTE), 
	"REQUEST_DATE" TIMESTAMP (6), 
	"STATUS" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" 
 LOB ("FORM_DATA") STORE AS BASICFILE (
  TABLESPACE "HADB_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
--------------------------------------------------------
--  DDL for Table HEALTH_ADVOCATE_LOGIN
--------------------------------------------------------

  CREATE TABLE "HADB"."HEALTH_ADVOCATE_LOGIN" 
   (	"USERID" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"PASSWORD_EXPIRED_DATE" TIMESTAMP (6), 
	"SUD_ACCEPTED_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table HEALTH_ADVOCATE_REQUEST
--------------------------------------------------------

  CREATE TABLE "HADB"."HEALTH_ADVOCATE_REQUEST" 
   (	"HEALTH_ADVOCATE_REQUEST_ID" VARCHAR2(32 BYTE), 
	"HEALTH_ADVOCATE_EDIPI" VARCHAR2(255 BYTE), 
	"PATIENT_EDIPI" VARCHAR2(255 BYTE), 
	"URI_LINK_KEY" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"FIRST_NAME" VARCHAR2(255 BYTE), 
	"LAST_NAME" VARCHAR2(255 BYTE), 
	"ADDRESS_FIRST_LINE" VARCHAR2(255 BYTE), 
	"ADDRESS_SECOND_LINE" VARCHAR2(255 BYTE), 
	"CITY" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(20 BYTE), 
	"ZIP_CODE" VARCHAR2(10 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"REQUEST_DATE" TIMESTAMP (6), 
	"LAST_ACTION_DATE" TIMESTAMP (6), 
	"PATIENT_NAME" VARCHAR2(255 BYTE), 
	"DRIVERS_LICENSE_NUMBER" VARCHAR2(255 BYTE), 
	"DRIVERS_LICENSE_STATE" VARCHAR2(255 BYTE), 
	"PATIENT_DISPLAY_NAME" VARCHAR2(255 BYTE), 
	"SSN" VARCHAR2(30 BYTE), 
	"COMMENTS" VARCHAR2(150 BYTE), 
	"VBA_STATUS" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table LAUNCHPAD_ITEM
--------------------------------------------------------

  CREATE TABLE "HADB"."LAUNCHPAD_ITEM" 
   (	"NAME" VARCHAR2(50 BYTE), 
	"ITEM_MODE" VARCHAR2(50 BYTE), 
	"TYPE" VARCHAR2(50 BYTE), 
	"ITEM_POSITION" NUMBER(10,0), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"URL" VARCHAR2(2000 BYTE), 
	"IMAGE_URL" VARCHAR2(2000 BYTE), 
	"INSTRUCTION" VARCHAR2(4000 BYTE), 
	"INSTR_UPDATED_DATE" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table MEDICATION_REFILL_REQUEST
--------------------------------------------------------

  CREATE TABLE "HADB"."MEDICATION_REFILL_REQUEST" 
   (	"ID" VARCHAR2(32 BYTE), 
	"PATIENT_ID" VARCHAR2(255 BYTE), 
	"MEDICATION_ID" VARCHAR2(255 BYTE), 
	"REQUEST_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table METRIC
--------------------------------------------------------

  CREATE TABLE "HADB"."METRIC" 
   (	"ID" VARCHAR2(40 BYTE), 
	"METRIC_NAME" VARCHAR2(1000 BYTE), 
	"TIMING" NUMBER(11,0), 
	"PARENT_EVENT_ID" VARCHAR2(40 BYTE), 
	"START_DATE" TIMESTAMP (6), 
	"END_DATE" TIMESTAMP (6), 
	"START_TICKS" NUMBER(20,0), 
	"END_TICKS" NUMBER(20,0), 
	"RESULT" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table METRIC_DATA
--------------------------------------------------------

  CREATE TABLE "HADB"."METRIC_DATA" 
   (	"ID" RAW(16), 
	"METRIC_ID" VARCHAR2(40 BYTE), 
	"TAG" VARCHAR2(100 BYTE), 
	"VALUE" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table MOOD
--------------------------------------------------------

  CREATE TABLE "HADB"."MOOD" 
   (	"ID" VARCHAR2(32 BYTE), 
	"PATIENT_ID" VARCHAR2(255 BYTE), 
	"MOOD" VARCHAR2(20 BYTE), 
	"ENTRY_DATE" DATE, 
	"NOTE" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" 
 LOB ("NOTE") STORE AS BASICFILE (
  TABLESPACE "HADB_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
--------------------------------------------------------
--  DDL for Table MYGOALS
--------------------------------------------------------

  CREATE TABLE "HADB"."MYGOALS" 
   (	"MYGOALS_ID" VARCHAR2(32 BYTE), 
	"PATIENT_ID" VARCHAR2(255 BYTE), 
	"INVENTORY_TYPE" VARCHAR2(255 BYTE), 
	"QUESTION_KEY" VARCHAR2(32 BYTE), 
	"ANSWER" VARCHAR2(4000 BYTE), 
	"DATE_UPDATED" TIMESTAMP (6), 
	"ELAPSED_TIME" NUMBER(32,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table NOTIFICATION
--------------------------------------------------------

  CREATE TABLE "HADB"."NOTIFICATION" 
   (	"NOTIFICATION_ID" VARCHAR2(32 BYTE), 
	"USER_ID" VARCHAR2(255 BYTE), 
	"BODY" VARCHAR2(4000 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"ACTIVE" NUMBER(1,0), 
	"DELETED_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table NOTIFICATION_PREFERENCE
--------------------------------------------------------

  CREATE TABLE "HADB"."NOTIFICATION_PREFERENCE" 
   (	"PATIENT_ID" VARCHAR2(255 BYTE), 
	"NOTIFICATION_FREQUENCY" VARCHAR2(255 BYTE), 
	"EMAIL_ALLOWED" NUMBER(1,0), 
	"EMAIL_ADDRESS" VARCHAR2(255 BYTE), 
	"TEXT_MESSAGING_ALLOWED" NUMBER(1,0), 
	"TEXT_MESSAGING_PHONE_NUMBER" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table PAIN_GOALS
--------------------------------------------------------

  CREATE TABLE "HADB"."PAIN_GOALS" 
   (	"PAIN_GOAL_ID" VARCHAR2(32 BYTE), 
	"DATE_STARTED" TIMESTAMP (6), 
	"NAME" VARCHAR2(255 BYTE), 
	"GOAL_STATUS" VARCHAR2(255 BYTE), 
	"PERCENT_COMPLETE" VARCHAR2(255 BYTE), 
	"GOAL_TYPE" VARCHAR2(255 BYTE), 
	"DETAILS" VARCHAR2(255 BYTE), 
	"PATIENT_ID" VARCHAR2(255 BYTE), 
	"NEXT_ACTION_STEP" VARCHAR2(4000 BYTE), 
	"TARGET_DATE" TIMESTAMP (6), 
	"DATE_DELETED" TIMESTAMP (6), 
	"DATE_COMPLETED" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table PAIN_GOAL_ENTRIES
--------------------------------------------------------

  CREATE TABLE "HADB"."PAIN_GOAL_ENTRIES" 
   (	"PAIN_GOAL_ENTRY_ID" VARCHAR2(32 BYTE), 
	"ENTRY_DATE" TIMESTAMP (6), 
	"COMMENTS" VARCHAR2(4000 BYTE), 
	"PERCENT_COMPLETE" VARCHAR2(255 BYTE), 
	"PAIN_GOAL_ID" VARCHAR2(32 BYTE), 
	"STATUS" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table PATIENT
--------------------------------------------------------

  CREATE TABLE "HADB"."PATIENT" 
   (	"PATIENT_ID" VARCHAR2(255 BYTE), 
	"FIRST_NAME" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(100 BYTE), 
	"SSN" VARCHAR2(20 BYTE), 
	"DATE_OF_BIRTH" TIMESTAMP (6), 
	"TEXT_MESSAGING_ALLOWED" NUMBER(1,0), 
	"TEXT_MESSAGING_PHONE_NUMBER" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table PATIENT_EDIPI_ICN
--------------------------------------------------------

  CREATE TABLE "HADB"."PATIENT_EDIPI_ICN" 
   (	"ID" RAW(16), 
	"EDIPI" VARCHAR2(255 BYTE), 
	"ICN" VARCHAR2(255 BYTE), 
	"ACTIVE" NUMBER(1,0), 
	"CREATED_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table PATIENT_METADATA
--------------------------------------------------------

  CREATE TABLE "HADB"."PATIENT_METADATA" 
   (	"PATIENT_ID" VARCHAR2(255 BYTE), 
	"LAST_APPT_REQ_ACCESS_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table PUBLIC_KEY
--------------------------------------------------------

  CREATE TABLE "HADB"."PUBLIC_KEY" 
   (	"PUBLIC_KEY" VARCHAR2(255 BYTE), 
	"USER_ID" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table RESPONSES
--------------------------------------------------------

  CREATE TABLE "HADB"."RESPONSES" 
   (	"RESPONSE_ID" VARCHAR2(32 BYTE), 
	"RESPONSE" VARCHAR2(255 BYTE), 
	"QUESTION_ID" VARCHAR2(255 BYTE), 
	"ENTRY_ID" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table STAFF_USER_DISCLAIMER
--------------------------------------------------------

  CREATE TABLE "HADB"."STAFF_USER_DISCLAIMER" 
   (	"USER_ID" VARCHAR2(255 BYTE), 
	"VISTA_LOCATION" VARCHAR2(255 BYTE), 
	"SUD_STATE" NUMBER(1,0), 
	"SUD_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table STAFF_USER_DISCLAIMER_CONTENT
--------------------------------------------------------

  CREATE TABLE "HADB"."STAFF_USER_DISCLAIMER_CONTENT" 
   (	"CREATED_DATE" TIMESTAMP (6), 
	"CONTENT" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table TOOL_TRACKING_RESULT
--------------------------------------------------------

  CREATE TABLE "HADB"."TOOL_TRACKING_RESULT" 
   (	"TOOL_TRACKING_RESULT_ID" VARCHAR2(32 BYTE), 
	"PATIENT_ID" VARCHAR2(255 BYTE), 
	"TOOL" VARCHAR2(255 BYTE), 
	"FREQUENCY" VARCHAR2(255 BYTE), 
	"USEFULNESS" VARCHAR2(255 BYTE), 
	"SUCCESS_RATE" VARCHAR2(255 BYTE), 
	"DATE_TRACKED" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table USER_FEEDBACK
--------------------------------------------------------

  CREATE TABLE "HADB"."USER_FEEDBACK" 
   (	"USER_FEEDBACK_ID" VARCHAR2(32 BYTE), 
	"RATING" NUMBER(3,0), 
	"APPT_PROCESSED_TIMELY" VARCHAR2(32 BYTE), 
	"COMMENTS" CLOB, 
	"CREATED_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" 
 LOB ("COMMENTS") STORE AS BASICFILE (
  TABLESPACE "HADB_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
--------------------------------------------------------
--  DDL for Table USER_HISTORY
--------------------------------------------------------

  CREATE TABLE "HADB"."USER_HISTORY" 
   (	"ID" RAW(16), 
	"USER_ID" VARCHAR2(255 BYTE), 
	"TABLE_NAME" VARCHAR2(255 BYTE), 
	"ROW_ID" RAW(16), 
	"OPERATION" VARCHAR2(255 BYTE), 
	"ACTION_DATE" TIMESTAMP (6), 
	"DATA" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" 
 LOB ("DATA") STORE AS BASICFILE (
  TABLESPACE "HADB_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
--------------------------------------------------------
--  DDL for Table USER_LAST_ACCESSED_TIME
--------------------------------------------------------

  CREATE TABLE "HADB"."USER_LAST_ACCESSED_TIME" 
   (	"USER_ID" VARCHAR2(255 BYTE), 
	"LAST_ACCESSED_TIME" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table USER_RIGHTOFACCESS
--------------------------------------------------------

  CREATE TABLE "HADB"."USER_RIGHTOFACCESS" 
   (	"USER_ID" VARCHAR2(255 BYTE), 
	"ROA_STATE" NUMBER(1,0), 
	"ROA_DATE" TIMESTAMP (6), 
	"ROA_FORM" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" 
 LOB ("ROA_FORM") STORE AS BASICFILE (
  TABLESPACE "HADB_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table VITAL_ENTRY
--------------------------------------------------------

  CREATE TABLE "HADB"."VITAL_ENTRY" 
   (	"VITAL_ENTRY_ID" VARCHAR2(32 BYTE), 
	"PATIENT_ID" VARCHAR2(255 BYTE), 
	"SECTION" VARCHAR2(255 BYTE), 
	"QUALIFIER" VARCHAR2(255 BYTE), 
	"NOTES" VARCHAR2(4000 BYTE), 
	"ENTRY_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Table VITAL_OBSERVATION
--------------------------------------------------------

  CREATE TABLE "HADB"."VITAL_OBSERVATION" 
   (	"VITAL_OBSERVATION_ID" VARCHAR2(32 BYTE), 
	"TYPE" VARCHAR2(255 BYTE), 
	"VALUE" VARCHAR2(255 BYTE), 
	"UNITS" VARCHAR2(255 BYTE), 
	"VITAL_ENTRY_ID" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HADB_DATA" ;

--------------------------------------------------------
--  DDL for Index APPT_REQ_MSG_PK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."APPT_REQ_MSG_PK_ID" ON "HADB"."APPOINTMENT_REQUEST_MESSAGE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index ASSESSMENTS_PK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."ASSESSMENTS_PK_ID" ON "HADB"."ASSESSMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index ASSESSMENT_QUESTIONS_PK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."ASSESSMENT_QUESTIONS_PK_ID" ON "HADB"."ASSESSMENT_QUESTIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index CALENDAR_EVENTS_IDX_PATIENT_ID
--------------------------------------------------------

  CREATE INDEX "HADB"."CALENDAR_EVENTS_IDX_PATIENT_ID" ON "HADB"."CALENDAR_EVENTS" ("PATIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index CALENDAR_EVENTS_PK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."CALENDAR_EVENTS_PK_ID" ON "HADB"."CALENDAR_EVENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index COMMUNICATIONS_IDX_LOG_TIME
--------------------------------------------------------

  CREATE INDEX "HADB"."COMMUNICATIONS_IDX_LOG_TIME" ON "HADB"."COMMUNICATIONS" ("LOG_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index COMMUNICATIONS_IDX_PATIENT_ID
--------------------------------------------------------

  CREATE INDEX "HADB"."COMMUNICATIONS_IDX_PATIENT_ID" ON "HADB"."COMMUNICATIONS" ("PATIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index COMMUNICATION_PK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."COMMUNICATION_PK_ID" ON "HADB"."COMMUNICATIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index DAILY_EVENT_IDX_PATIENT_ID
--------------------------------------------------------

  CREATE INDEX "HADB"."DAILY_EVENT_IDX_PATIENT_ID" ON "HADB"."DAILY_EVENT" ("PATIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index DAILY_EVENT_PK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."DAILY_EVENT_PK_ID" ON "HADB"."DAILY_EVENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index DIET_IDX_PATIENT_ID
--------------------------------------------------------

  CREATE INDEX "HADB"."DIET_IDX_PATIENT_ID" ON "HADB"."DIET" ("PATIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index DIET_PK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."DIET_PK_ID" ON "HADB"."DIET" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index DOCUMENTS_IDX_ENTRY_ID
--------------------------------------------------------

  CREATE INDEX "HADB"."DOCUMENTS_IDX_ENTRY_ID" ON "HADB"."DOCUMENTS" ("ENTRY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index DOCUMENTS_IDX_PATIENT_ID
--------------------------------------------------------

  CREATE INDEX "HADB"."DOCUMENTS_IDX_PATIENT_ID" ON "HADB"."DOCUMENTS" ("PATIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index DOCUMENTS_PK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."DOCUMENTS_PK_ID" ON "HADB"."DOCUMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index EXERCISE_IDX_PATIENT_ID
--------------------------------------------------------

  CREATE INDEX "HADB"."EXERCISE_IDX_PATIENT_ID" ON "HADB"."EXERCISE" ("PATIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index EXERCISE_PK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."EXERCISE_PK_ID" ON "HADB"."EXERCISE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index HEALTH_ADVOCATE_LOGIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."HEALTH_ADVOCATE_LOGIN_PK" ON "HADB"."HEALTH_ADVOCATE_LOGIN" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_MEDREQ_MED_ID
--------------------------------------------------------

  CREATE INDEX "HADB"."IDX_MEDREQ_MED_ID" ON "HADB"."MEDICATION_REFILL_REQUEST" ("MEDICATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_MEDREQ_PAT_ID
--------------------------------------------------------

  CREATE INDEX "HADB"."IDX_MEDREQ_PAT_ID" ON "HADB"."MEDICATION_REFILL_REQUEST" ("PATIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_PATIENT_EDIPI
--------------------------------------------------------

  CREATE INDEX "HADB"."IDX_PATIENT_EDIPI" ON "HADB"."HEALTH_ADVOCATE_REQUEST" ("PATIENT_EDIPI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_STATUS
--------------------------------------------------------

  CREATE INDEX "HADB"."IDX_STATUS" ON "HADB"."HEALTH_ADVOCATE_REQUEST" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_TOOL_TRACKING_PAT_ID
--------------------------------------------------------

  CREATE INDEX "HADB"."IDX_TOOL_TRACKING_PAT_ID" ON "HADB"."TOOL_TRACKING_RESULT" ("PATIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_TOOL_TRACKING_TOOL
--------------------------------------------------------

  CREATE INDEX "HADB"."IDX_TOOL_TRACKING_TOOL" ON "HADB"."TOOL_TRACKING_RESULT" ("TOOL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index LAST_ACCESSED_USR_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."LAST_ACCESSED_USR_ID_PK" ON "HADB"."USER_LAST_ACCESSED_TIME" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index MOOD_IDX_ENTRY_DATE
--------------------------------------------------------

  CREATE INDEX "HADB"."MOOD_IDX_ENTRY_DATE" ON "HADB"."MOOD" ("ENTRY_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index MOOD_IDX_PATIENT_ID
--------------------------------------------------------

  CREATE INDEX "HADB"."MOOD_IDX_PATIENT_ID" ON "HADB"."MOOD" ("PATIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index MOOD_PK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."MOOD_PK_ID" ON "HADB"."MOOD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PATIENT_EDIPI_ICN_PK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PATIENT_EDIPI_ICN_PK_ID" ON "HADB"."PATIENT_EDIPI_ICN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_APPOINTMENT_METRICS
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_APPOINTMENT_METRICS" ON "HADB"."APPOINTMENT_METRICS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_APPOINTMENT_REQUEST
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_APPOINTMENT_REQUEST" ON "HADB"."APPOINTMENT_REQUEST" ("APPOINTMENT_REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_APPT_REQ_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_APPT_REQ_ID" ON "HADB"."APPT_REQ_INPROCESS" ("APPT_REQ_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_ARDC_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_ARDC_ID" ON "HADB"."AR_DETAIL_CODE" ("AR_DETAIL_CODE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_ASSESSMENT_RESULT
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_ASSESSMENT_RESULT" ON "HADB"."ASSESSMENT_RESULT" ("ASSESSMENT_RESULT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_AUDIT_LOG
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_AUDIT_LOG" ON "HADB"."AUDIT_LOG" ("AUDIT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_BEST_TIME
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_BEST_TIME" ON "HADB"."BEST_TIME_TO_CALL" ("APPOINTMENT_REQUEST_ID", "BEST_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_DETAIL_CODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_DETAIL_CODE" ON "HADB"."DETAIL_CODE" ("DETAIL_CODE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_DEVICE_REGISTRATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_DEVICE_REGISTRATION" ON "HADB"."DEVICE_REGISTRATION" ("DEVICE_REGISTRATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_ENTRY
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_ENTRY" ON "HADB"."ENTRIES" ("ENTRY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_FACILITY
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_FACILITY" ON "HADB"."FACILITY" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_HEALTH_ADVOCATE_REQUEST
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_HEALTH_ADVOCATE_REQUEST" ON "HADB"."HEALTH_ADVOCATE_REQUEST" ("HEALTH_ADVOCATE_REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_LAUNCHPAD_ITEM
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_LAUNCHPAD_ITEM" ON "HADB"."LAUNCHPAD_ITEM" ("NAME", "ITEM_MODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_MED_REFILL_REQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_MED_REFILL_REQ" ON "HADB"."MEDICATION_REFILL_REQUEST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_MYGOALS
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_MYGOALS" ON "HADB"."MYGOALS" ("MYGOALS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_NOTIFICATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_NOTIFICATION" ON "HADB"."NOTIFICATION" ("NOTIFICATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_NOTIFICATION_PREFERENCE
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_NOTIFICATION_PREFERENCE" ON "HADB"."NOTIFICATION_PREFERENCE" ("PATIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_PAIN_GOAL
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_PAIN_GOAL" ON "HADB"."PAIN_GOALS" ("PAIN_GOAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_PAIN_GOAL_ENTRY
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_PAIN_GOAL_ENTRY" ON "HADB"."PAIN_GOAL_ENTRIES" ("PAIN_GOAL_ENTRY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_PATIENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_PATIENT" ON "HADB"."PATIENT" ("PATIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_PATIENT_METADATA_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_PATIENT_METADATA_ID" ON "HADB"."PATIENT_METADATA" ("PATIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_PUBLIC_KEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_PUBLIC_KEY" ON "HADB"."PUBLIC_KEY" ("PUBLIC_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_RESPONSE
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_RESPONSE" ON "HADB"."RESPONSES" ("RESPONSE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_TOOL_TRACKING_RESULT_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_TOOL_TRACKING_RESULT_ID" ON "HADB"."TOOL_TRACKING_RESULT" ("TOOL_TRACKING_RESULT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_USER_FEEDBACK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_USER_FEEDBACK_ID" ON "HADB"."USER_FEEDBACK" ("USER_FEEDBACK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_USER_RIGHTOFACCESS
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_USER_RIGHTOFACCESS" ON "HADB"."USER_RIGHTOFACCESS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_VITAL_ENTRY
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_VITAL_ENTRY" ON "HADB"."VITAL_ENTRY" ("VITAL_ENTRY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_VITAL_OBSERVATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_VITAL_OBSERVATION" ON "HADB"."VITAL_OBSERVATION" ("VITAL_OBSERVATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index STAFF_USER_DISCLAIMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."STAFF_USER_DISCLAIMER_PK" ON "HADB"."STAFF_USER_DISCLAIMER" ("USER_ID", "VISTA_LOCATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index SUD_CONTENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."SUD_CONTENT_PK" ON "HADB"."STAFF_USER_DISCLAIMER_CONTENT" ("CREATED_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0016331
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."SYS_C0016331" ON "HADB"."ANNIEJMSSTOREWLSTORE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index UC_LP_ITEM_POSITION
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."UC_LP_ITEM_POSITION" ON "HADB"."LAUNCHPAD_ITEM" ("ITEM_MODE", "ITEM_POSITION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index USER_HISTORY_IDX_ACTION_DATE
--------------------------------------------------------

  CREATE INDEX "HADB"."USER_HISTORY_IDX_ACTION_DATE" ON "HADB"."USER_HISTORY" ("ACTION_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index USER_HISTORY_IDX_USER_ID
--------------------------------------------------------

  CREATE INDEX "HADB"."USER_HISTORY_IDX_USER_ID" ON "HADB"."USER_HISTORY" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index USER_HISTORY_PK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."USER_HISTORY_PK_ID" ON "HADB"."USER_HISTORY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_DATABASECHANGELOG
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_DATABASECHANGELOG" ON "HADB"."DATABASECHANGELOG" ("ID", "AUTHOR", "FILENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_DATABASECHANGELOGLOCK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_DATABASECHANGELOGLOCK" ON "HADB"."DATABASECHANGELOGLOCK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index METRIC_DATA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."METRIC_DATA_PK" ON "HADB"."METRIC_DATA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_METRIC
--------------------------------------------------------

  CREATE UNIQUE INDEX "HADB"."PK_METRIC" ON "HADB"."METRIC" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA" ;

/*
  Commit the created tables and indices before altering tables that may not exist yet
 */

COMMIT;

--------------------------------------------------------
--  Constraints for Table ANNIEJMSSTOREWLSTORE
--------------------------------------------------------

  ALTER TABLE "HADB"."ANNIEJMSSTOREWLSTORE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."ANNIEJMSSTOREWLSTORE" MODIFY ("RECORD" NOT NULL ENABLE);
  ALTER TABLE "HADB"."ANNIEJMSSTOREWLSTORE" MODIFY ("HANDLE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."ANNIEJMSSTOREWLSTORE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."ANNIEJMSSTOREWLSTORE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APPOINTMENT_METRICS
--------------------------------------------------------

  ALTER TABLE "HADB"."APPOINTMENT_METRICS" ADD CONSTRAINT "PK_APPOINTMENT_METRICS" PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."APPOINTMENT_METRICS" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_METRICS" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APPOINTMENT_REQUEST
--------------------------------------------------------

  ALTER TABLE "HADB"."APPOINTMENT_REQUEST" ADD CONSTRAINT "PK_APPOINTMENT_REQUEST" PRIMARY KEY ("APPOINTMENT_REQUEST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST" MODIFY ("SECOND_REQUEST_SUBMITTED" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST" MODIFY ("PROVIDER_NAME" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST" MODIFY ("PROVIDER_ID" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST" MODIFY ("VISIT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST" MODIFY ("PURPOSE_OF_VISIT" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST" MODIFY ("TEXT_MESSAGING_ALLOWED" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST" MODIFY ("FACILITY_CODE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST" MODIFY ("APPOINTMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST" MODIFY ("OPTION_TIME_3" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST" MODIFY ("OPTION_DATE_3" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST" MODIFY ("OPTION_TIME_2" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST" MODIFY ("OPTION_DATE_2" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST" MODIFY ("OPTION_TIME_1" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST" MODIFY ("OPTION_DATE_1" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST" MODIFY ("SECOND_REQUEST" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST" MODIFY ("ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST" MODIFY ("LAST_UPDATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST" MODIFY ("APPOINTMENT_REQUEST_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APPOINTMENT_REQUEST_MESSAGE
--------------------------------------------------------

  ALTER TABLE "HADB"."APPOINTMENT_REQUEST_MESSAGE" ADD CONSTRAINT "APPT_REQ_MSG_PK_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST_MESSAGE" MODIFY ("MESSAGE_DATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST_MESSAGE" MODIFY ("MESSAGE_TEXT" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST_MESSAGE" MODIFY ("SENDER_ID" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST_MESSAGE" MODIFY ("APPOINTMENT_REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPOINTMENT_REQUEST_MESSAGE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APPT_REQ_INPROCESS
--------------------------------------------------------

  ALTER TABLE "HADB"."APPT_REQ_INPROCESS" ADD CONSTRAINT "PK_APPT_REQ_ID" PRIMARY KEY ("APPT_REQ_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."APPT_REQ_INPROCESS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPT_REQ_INPROCESS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPT_REQ_INPROCESS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "HADB"."APPT_REQ_INPROCESS" MODIFY ("APPT_REQ_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AR_DETAIL_CODE
--------------------------------------------------------

  ALTER TABLE "HADB"."AR_DETAIL_CODE" ADD CONSTRAINT "PK_ARDC_ID" PRIMARY KEY ("AR_DETAIL_CODE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."AR_DETAIL_CODE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "HADB"."AR_DETAIL_CODE" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."AR_DETAIL_CODE" MODIFY ("APPOINTMENT_REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "HADB"."AR_DETAIL_CODE" MODIFY ("DETAIL_CODE_ID" NOT NULL ENABLE);
  ALTER TABLE "HADB"."AR_DETAIL_CODE" MODIFY ("AR_DETAIL_CODE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASSESSMENTS
--------------------------------------------------------

  ALTER TABLE "HADB"."ASSESSMENTS" ADD CONSTRAINT "ASSESSMENTS_PK_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."ASSESSMENTS" MODIFY ("WAITING_PERIOD" NOT NULL ENABLE);
  ALTER TABLE "HADB"."ASSESSMENTS" MODIFY ("AUTHENTICATION_STRATEGY" NOT NULL ENABLE);
  ALTER TABLE "HADB"."ASSESSMENTS" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "HADB"."ASSESSMENTS" MODIFY ("UNIQUE_TITLE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."ASSESSMENTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASSESSMENT_QUESTIONS
--------------------------------------------------------

  ALTER TABLE "HADB"."ASSESSMENT_QUESTIONS" ADD CONSTRAINT "ASSESSMENT_QUESTIONS_PK_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."ASSESSMENT_QUESTIONS" MODIFY ("ASSESSMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HADB"."ASSESSMENT_QUESTIONS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASSESSMENT_RESULT
--------------------------------------------------------

  ALTER TABLE "HADB"."ASSESSMENT_RESULT" ADD CONSTRAINT "PK_ASSESSMENT_RESULT" PRIMARY KEY ("ASSESSMENT_RESULT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."ASSESSMENT_RESULT" MODIFY ("WAITING_PERIOD" NOT NULL ENABLE);
  ALTER TABLE "HADB"."ASSESSMENT_RESULT" MODIFY ("AUTHENTICATION_STRATEGY" NOT NULL ENABLE);
  ALTER TABLE "HADB"."ASSESSMENT_RESULT" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "HADB"."ASSESSMENT_RESULT" MODIFY ("UNIQUE_TITLE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."ASSESSMENT_RESULT" MODIFY ("ASSESSMENT_RESULT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUDIT_LOG
--------------------------------------------------------

  ALTER TABLE "HADB"."AUDIT_LOG" ADD CONSTRAINT "PK_AUDIT_LOG" PRIMARY KEY ("AUDIT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."AUDIT_LOG" MODIFY ("AUDIT_DATE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."AUDIT_LOG" MODIFY ("AUDIT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BEST_TIME_TO_CALL
--------------------------------------------------------

  ALTER TABLE "HADB"."BEST_TIME_TO_CALL" ADD CONSTRAINT "PK_BEST_TIME" PRIMARY KEY ("APPOINTMENT_REQUEST_ID", "BEST_TIME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."BEST_TIME_TO_CALL" MODIFY ("BEST_TIME" NOT NULL ENABLE);
  ALTER TABLE "HADB"."BEST_TIME_TO_CALL" MODIFY ("APPOINTMENT_REQUEST_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CALENDAR_EVENTS
--------------------------------------------------------

  ALTER TABLE "HADB"."CALENDAR_EVENTS" ADD CONSTRAINT "CALENDAR_EVENTS_PK_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."CALENDAR_EVENTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMUNICATIONS
--------------------------------------------------------

  ALTER TABLE "HADB"."COMMUNICATIONS" ADD CONSTRAINT "COMMUNICATION_PK_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."COMMUNICATIONS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DAILY_EVENT
--------------------------------------------------------

  ALTER TABLE "HADB"."DAILY_EVENT" ADD CONSTRAINT "DAILY_EVENT_PK_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."DAILY_EVENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DATABASECHANGELOG
--------------------------------------------------------

  ALTER TABLE "HADB"."DATABASECHANGELOG" ADD CONSTRAINT "PK_DATABASECHANGELOG" PRIMARY KEY ("ID", "AUTHOR", "FILENAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."DATABASECHANGELOG" MODIFY ("EXECTYPE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."DATABASECHANGELOG" MODIFY ("ORDEREXECUTED" NOT NULL ENABLE);
  ALTER TABLE "HADB"."DATABASECHANGELOG" MODIFY ("DATEEXECUTED" NOT NULL ENABLE);
  ALTER TABLE "HADB"."DATABASECHANGELOG" MODIFY ("FILENAME" NOT NULL ENABLE);
  ALTER TABLE "HADB"."DATABASECHANGELOG" MODIFY ("AUTHOR" NOT NULL ENABLE);
  ALTER TABLE "HADB"."DATABASECHANGELOG" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DATABASECHANGELOGLOCK
--------------------------------------------------------

  ALTER TABLE "HADB"."DATABASECHANGELOGLOCK" ADD CONSTRAINT "PK_DATABASECHANGELOGLOCK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."DATABASECHANGELOGLOCK" MODIFY ("LOCKED" NOT NULL ENABLE);
  ALTER TABLE "HADB"."DATABASECHANGELOGLOCK" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETAIL_CODE
--------------------------------------------------------

  ALTER TABLE "HADB"."DETAIL_CODE" ADD CONSTRAINT "PK_DETAIL_CODE" PRIMARY KEY ("DETAIL_CODE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."DETAIL_CODE" MODIFY ("VETERAN_MESSAGE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."DETAIL_CODE" MODIFY ("PROVIDER_MESSAGE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."DETAIL_CODE" MODIFY ("DETAIL_CODE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEVICE_REGISTRATION
--------------------------------------------------------

  ALTER TABLE "HADB"."DEVICE_REGISTRATION" ADD CONSTRAINT "PK_DEVICE_REGISTRATION" PRIMARY KEY ("DEVICE_REGISTRATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."DEVICE_REGISTRATION" MODIFY ("OPTED_IN_FLAG" NOT NULL ENABLE);
  ALTER TABLE "HADB"."DEVICE_REGISTRATION" MODIFY ("DEVICE_TOKEN" NOT NULL ENABLE);
  ALTER TABLE "HADB"."DEVICE_REGISTRATION" MODIFY ("REGISTERED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."DEVICE_REGISTRATION" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "HADB"."DEVICE_REGISTRATION" MODIFY ("DEVICE_REGISTRATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DIET
--------------------------------------------------------

  ALTER TABLE "HADB"."DIET" ADD CONSTRAINT "DIET_PK_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."DIET" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOCUMENTS
--------------------------------------------------------

  ALTER TABLE "HADB"."DOCUMENTS" ADD CONSTRAINT "DOCUMENTS_PK_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."DOCUMENTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENTRIES
--------------------------------------------------------

  ALTER TABLE "HADB"."ENTRIES" ADD CONSTRAINT "PK_ENTRY" PRIMARY KEY ("ENTRY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."ENTRIES" MODIFY ("DATE_CREATED" NOT NULL ENABLE);
  ALTER TABLE "HADB"."ENTRIES" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HADB"."ENTRIES" MODIFY ("COMPLETED" NOT NULL ENABLE);
  ALTER TABLE "HADB"."ENTRIES" MODIFY ("ENTRY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EXERCISE
--------------------------------------------------------

  ALTER TABLE "HADB"."EXERCISE" ADD CONSTRAINT "EXERCISE_PK_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."EXERCISE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FACILITY
--------------------------------------------------------

  ALTER TABLE "HADB"."FACILITY" ADD CONSTRAINT "PK_FACILITY" PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."FACILITY" MODIFY ("PARENT_SITE_CODE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."FACILITY" MODIFY ("FACILITY_CODE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."FACILITY" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HEALTH_ADVOCATE_FORM
--------------------------------------------------------

  ALTER TABLE "HADB"."HEALTH_ADVOCATE_FORM" MODIFY ("FORM_DATA" NOT NULL ENABLE);
  ALTER TABLE "HADB"."HEALTH_ADVOCATE_FORM" MODIFY ("HEALTH_ADVOCATE_REQUEST_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HEALTH_ADVOCATE_LOGIN
--------------------------------------------------------

  ALTER TABLE "HADB"."HEALTH_ADVOCATE_LOGIN" ADD CONSTRAINT "HEALTH_ADVOCATE_LOGIN_PK" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."HEALTH_ADVOCATE_LOGIN" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "HADB"."HEALTH_ADVOCATE_LOGIN" MODIFY ("USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HEALTH_ADVOCATE_REQUEST
--------------------------------------------------------

  ALTER TABLE "HADB"."HEALTH_ADVOCATE_REQUEST" ADD CONSTRAINT "PK_HEALTH_ADVOCATE_REQUEST" PRIMARY KEY ("HEALTH_ADVOCATE_REQUEST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."HEALTH_ADVOCATE_REQUEST" MODIFY ("PATIENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "HADB"."HEALTH_ADVOCATE_REQUEST" MODIFY ("REQUEST_DATE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."HEALTH_ADVOCATE_REQUEST" MODIFY ("ZIP_CODE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."HEALTH_ADVOCATE_REQUEST" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."HEALTH_ADVOCATE_REQUEST" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "HADB"."HEALTH_ADVOCATE_REQUEST" MODIFY ("ADDRESS_SECOND_LINE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."HEALTH_ADVOCATE_REQUEST" MODIFY ("ADDRESS_FIRST_LINE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."HEALTH_ADVOCATE_REQUEST" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "HADB"."HEALTH_ADVOCATE_REQUEST" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "HADB"."HEALTH_ADVOCATE_REQUEST" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "HADB"."HEALTH_ADVOCATE_REQUEST" MODIFY ("URI_LINK_KEY" NOT NULL ENABLE);
  ALTER TABLE "HADB"."HEALTH_ADVOCATE_REQUEST" MODIFY ("PATIENT_EDIPI" NOT NULL ENABLE);
  ALTER TABLE "HADB"."HEALTH_ADVOCATE_REQUEST" MODIFY ("HEALTH_ADVOCATE_EDIPI" NOT NULL ENABLE);
  ALTER TABLE "HADB"."HEALTH_ADVOCATE_REQUEST" MODIFY ("HEALTH_ADVOCATE_REQUEST_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LAUNCHPAD_ITEM
--------------------------------------------------------

  ALTER TABLE "HADB"."LAUNCHPAD_ITEM" ADD CONSTRAINT "UC_LP_ITEM_POSITION" UNIQUE ("ITEM_MODE", "ITEM_POSITION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."LAUNCHPAD_ITEM" ADD CONSTRAINT "PK_LAUNCHPAD_ITEM" PRIMARY KEY ("NAME", "ITEM_MODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."LAUNCHPAD_ITEM" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."LAUNCHPAD_ITEM" MODIFY ("ITEM_MODE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."LAUNCHPAD_ITEM" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDICATION_REFILL_REQUEST
--------------------------------------------------------

  ALTER TABLE "HADB"."MEDICATION_REFILL_REQUEST" ADD CONSTRAINT "PK_MED_REFILL_REQ" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."MEDICATION_REFILL_REQUEST" MODIFY ("REQUEST_DATE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."MEDICATION_REFILL_REQUEST" MODIFY ("MEDICATION_ID" NOT NULL ENABLE);
  ALTER TABLE "HADB"."MEDICATION_REFILL_REQUEST" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HADB"."MEDICATION_REFILL_REQUEST" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table METRIC
--------------------------------------------------------

  ALTER TABLE "HADB"."METRIC" ADD CONSTRAINT "PK_METRIC" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."METRIC" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table METRIC_DATA
--------------------------------------------------------

  ALTER TABLE "HADB"."METRIC_DATA" ADD CONSTRAINT "METRIC_DATA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."METRIC_DATA" MODIFY ("TAG" NOT NULL ENABLE);
  ALTER TABLE "HADB"."METRIC_DATA" MODIFY ("METRIC_ID" NOT NULL ENABLE);
  ALTER TABLE "HADB"."METRIC_DATA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MOOD
--------------------------------------------------------

  ALTER TABLE "HADB"."MOOD" ADD CONSTRAINT "MOOD_PK_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."MOOD" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MYGOALS
--------------------------------------------------------

  ALTER TABLE "HADB"."MYGOALS" ADD CONSTRAINT "PK_MYGOALS" PRIMARY KEY ("MYGOALS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."MYGOALS" MODIFY ("DATE_UPDATED" NOT NULL ENABLE);
  ALTER TABLE "HADB"."MYGOALS" MODIFY ("QUESTION_KEY" NOT NULL ENABLE);
  ALTER TABLE "HADB"."MYGOALS" MODIFY ("INVENTORY_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."MYGOALS" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HADB"."MYGOALS" MODIFY ("MYGOALS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "HADB"."NOTIFICATION" ADD CONSTRAINT "PK_NOTIFICATION" PRIMARY KEY ("NOTIFICATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."NOTIFICATION" MODIFY ("ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."NOTIFICATION" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."NOTIFICATION" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "HADB"."NOTIFICATION" MODIFY ("NOTIFICATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTIFICATION_PREFERENCE
--------------------------------------------------------

  ALTER TABLE "HADB"."NOTIFICATION_PREFERENCE" ADD CONSTRAINT "PK_NOTIFICATION_PREFERENCE" PRIMARY KEY ("PATIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."NOTIFICATION_PREFERENCE" MODIFY ("TEXT_MESSAGING_ALLOWED" NOT NULL ENABLE);
  ALTER TABLE "HADB"."NOTIFICATION_PREFERENCE" MODIFY ("EMAIL_ALLOWED" NOT NULL ENABLE);
  ALTER TABLE "HADB"."NOTIFICATION_PREFERENCE" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAIN_GOALS
--------------------------------------------------------

  ALTER TABLE "HADB"."PAIN_GOALS" ADD CONSTRAINT "PK_PAIN_GOAL" PRIMARY KEY ("PAIN_GOAL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."PAIN_GOALS" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HADB"."PAIN_GOALS" MODIFY ("GOAL_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."PAIN_GOALS" MODIFY ("GOAL_STATUS" NOT NULL ENABLE);
  ALTER TABLE "HADB"."PAIN_GOALS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HADB"."PAIN_GOALS" MODIFY ("PAIN_GOAL_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAIN_GOAL_ENTRIES
--------------------------------------------------------

  ALTER TABLE "HADB"."PAIN_GOAL_ENTRIES" ADD CONSTRAINT "PK_PAIN_GOAL_ENTRY" PRIMARY KEY ("PAIN_GOAL_ENTRY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."PAIN_GOAL_ENTRIES" MODIFY ("PAIN_GOAL_ID" NOT NULL ENABLE);
  ALTER TABLE "HADB"."PAIN_GOAL_ENTRIES" MODIFY ("COMMENTS" NOT NULL ENABLE);
  ALTER TABLE "HADB"."PAIN_GOAL_ENTRIES" MODIFY ("PAIN_GOAL_ENTRY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PATIENT
--------------------------------------------------------

  ALTER TABLE "HADB"."PATIENT" ADD CONSTRAINT "PK_PATIENT" PRIMARY KEY ("PATIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."PATIENT" MODIFY ("TEXT_MESSAGING_ALLOWED" NOT NULL ENABLE);
  ALTER TABLE "HADB"."PATIENT" MODIFY ("DATE_OF_BIRTH" NOT NULL ENABLE);
  ALTER TABLE "HADB"."PATIENT" MODIFY ("SSN" NOT NULL ENABLE);
  ALTER TABLE "HADB"."PATIENT" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "HADB"."PATIENT" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "HADB"."PATIENT" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PATIENT_EDIPI_ICN
--------------------------------------------------------

  ALTER TABLE "HADB"."PATIENT_EDIPI_ICN" ADD CONSTRAINT "PATIENT_EDIPI_ICN_PK_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."PATIENT_EDIPI_ICN" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PATIENT_METADATA
--------------------------------------------------------

  ALTER TABLE "HADB"."PATIENT_METADATA" ADD CONSTRAINT "PK_PATIENT_METADATA_ID" PRIMARY KEY ("PATIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."PATIENT_METADATA" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PUBLIC_KEY
--------------------------------------------------------

  ALTER TABLE "HADB"."PUBLIC_KEY" ADD CONSTRAINT "PK_PUBLIC_KEY" PRIMARY KEY ("PUBLIC_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."PUBLIC_KEY" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "HADB"."PUBLIC_KEY" MODIFY ("PUBLIC_KEY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESPONSES
--------------------------------------------------------

  ALTER TABLE "HADB"."RESPONSES" ADD CONSTRAINT "PK_RESPONSE" PRIMARY KEY ("RESPONSE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."RESPONSES" MODIFY ("ENTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "HADB"."RESPONSES" MODIFY ("QUESTION_ID" NOT NULL ENABLE);
  ALTER TABLE "HADB"."RESPONSES" MODIFY ("RESPONSE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."RESPONSES" MODIFY ("RESPONSE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STAFF_USER_DISCLAIMER
--------------------------------------------------------

  ALTER TABLE "HADB"."STAFF_USER_DISCLAIMER" ADD CONSTRAINT "STAFF_USER_DISCLAIMER_PK" PRIMARY KEY ("USER_ID", "VISTA_LOCATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."STAFF_USER_DISCLAIMER" MODIFY ("SUD_DATE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."STAFF_USER_DISCLAIMER" MODIFY ("SUD_STATE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."STAFF_USER_DISCLAIMER" MODIFY ("VISTA_LOCATION" NOT NULL ENABLE);
  ALTER TABLE "HADB"."STAFF_USER_DISCLAIMER" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STAFF_USER_DISCLAIMER_CONTENT
--------------------------------------------------------

  ALTER TABLE "HADB"."STAFF_USER_DISCLAIMER_CONTENT" ADD CONSTRAINT "SUD_CONTENT_PK" PRIMARY KEY ("CREATED_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."STAFF_USER_DISCLAIMER_CONTENT" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "HADB"."STAFF_USER_DISCLAIMER_CONTENT" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TOOL_TRACKING_RESULT
--------------------------------------------------------

  ALTER TABLE "HADB"."TOOL_TRACKING_RESULT" ADD CONSTRAINT "PK_TOOL_TRACKING_RESULT_ID" PRIMARY KEY ("TOOL_TRACKING_RESULT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."TOOL_TRACKING_RESULT" MODIFY ("TOOL_TRACKING_RESULT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_FEEDBACK
--------------------------------------------------------

  ALTER TABLE "HADB"."USER_FEEDBACK" ADD CONSTRAINT "PK_USER_FEEDBACK_ID" PRIMARY KEY ("USER_FEEDBACK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."USER_FEEDBACK" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."USER_FEEDBACK" MODIFY ("APPT_PROCESSED_TIMELY" NOT NULL ENABLE);
  ALTER TABLE "HADB"."USER_FEEDBACK" MODIFY ("RATING" NOT NULL ENABLE);
  ALTER TABLE "HADB"."USER_FEEDBACK" MODIFY ("USER_FEEDBACK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_HISTORY
--------------------------------------------------------

  ALTER TABLE "HADB"."USER_HISTORY" ADD CONSTRAINT "USER_HISTORY_PK_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."USER_HISTORY" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_LAST_ACCESSED_TIME
--------------------------------------------------------

  ALTER TABLE "HADB"."USER_LAST_ACCESSED_TIME" ADD CONSTRAINT "LAST_ACCESSED_USR_ID_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."USER_LAST_ACCESSED_TIME" MODIFY ("LAST_ACCESSED_TIME" NOT NULL ENABLE);
  ALTER TABLE "HADB"."USER_LAST_ACCESSED_TIME" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_RIGHTOFACCESS
--------------------------------------------------------

  ALTER TABLE "HADB"."USER_RIGHTOFACCESS" ADD CONSTRAINT "PK_USER_RIGHTOFACCESS" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."USER_RIGHTOFACCESS" MODIFY ("ROA_DATE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."USER_RIGHTOFACCESS" MODIFY ("ROA_STATE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."USER_RIGHTOFACCESS" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VITAL_ENTRY
--------------------------------------------------------

  ALTER TABLE "HADB"."VITAL_ENTRY" ADD CONSTRAINT "PK_VITAL_ENTRY" PRIMARY KEY ("VITAL_ENTRY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."VITAL_ENTRY" MODIFY ("SECTION" NOT NULL ENABLE);
  ALTER TABLE "HADB"."VITAL_ENTRY" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HADB"."VITAL_ENTRY" MODIFY ("VITAL_ENTRY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VITAL_OBSERVATION
--------------------------------------------------------

  ALTER TABLE "HADB"."VITAL_OBSERVATION" ADD CONSTRAINT "PK_VITAL_OBSERVATION" PRIMARY KEY ("VITAL_OBSERVATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HADB_DATA"  ENABLE;
  ALTER TABLE "HADB"."VITAL_OBSERVATION" MODIFY ("VITAL_ENTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "HADB"."VITAL_OBSERVATION" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."VITAL_OBSERVATION" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "HADB"."VITAL_OBSERVATION" MODIFY ("VITAL_OBSERVATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table AR_DETAIL_CODE
--------------------------------------------------------

  ALTER TABLE "HADB"."AR_DETAIL_CODE" ADD CONSTRAINT "FK_ARDC_APPT_REQ_ID" FOREIGN KEY ("APPOINTMENT_REQUEST_ID")
	  REFERENCES "HADB"."APPOINTMENT_REQUEST" ("APPOINTMENT_REQUEST_ID") ENABLE;
  ALTER TABLE "HADB"."AR_DETAIL_CODE" ADD CONSTRAINT "FK_ARDC_DETAIL_CODE" FOREIGN KEY ("DETAIL_CODE_ID")
	  REFERENCES "HADB"."DETAIL_CODE" ("DETAIL_CODE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BEST_TIME_TO_CALL
--------------------------------------------------------

  ALTER TABLE "HADB"."BEST_TIME_TO_CALL" ADD CONSTRAINT "FK_BTTC_APPT_REQ_ID" FOREIGN KEY ("APPOINTMENT_REQUEST_ID")
	  REFERENCES "HADB"."APPOINTMENT_REQUEST" ("APPOINTMENT_REQUEST_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table METRIC_DATA
--------------------------------------------------------

  ALTER TABLE "HADB"."METRIC_DATA" ADD CONSTRAINT "FK_METRIC_DATA_METRIC" FOREIGN KEY ("METRIC_ID")
	  REFERENCES "HADB"."METRIC" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAIN_GOAL_ENTRIES
--------------------------------------------------------

  ALTER TABLE "HADB"."PAIN_GOAL_ENTRIES" ADD CONSTRAINT "FK_GOAL_ID" FOREIGN KEY ("PAIN_GOAL_ID")
	  REFERENCES "HADB"."PAIN_GOALS" ("PAIN_GOAL_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPONSES
--------------------------------------------------------

  ALTER TABLE "HADB"."RESPONSES" ADD CONSTRAINT "FK_ENTRY_ID" FOREIGN KEY ("ENTRY_ID")
	  REFERENCES "HADB"."ENTRIES" ("ENTRY_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VITAL_OBSERVATION
--------------------------------------------------------

  ALTER TABLE "HADB"."VITAL_OBSERVATION" ADD CONSTRAINT "FK_VITAL_ENTRY" FOREIGN KEY ("VITAL_ENTRY_ID")
	  REFERENCES "HADB"."VITAL_ENTRY" ("VITAL_ENTRY_ID") ENABLE;
