DROP TABLE MOCKDB.MOCK_USER_PAT_ID;
DROP TABLE MOCKDB.DATABASECHANGELOG;
DROP TABLE MOCKDB.DATABASECHANGELOGLOCK;
DROP TABLE MOCKDB.ALLINSTITUTIONS;
DROP TABLE MOCKDB.MOCK_USERS;
DROP TABLE MOCKDB.MOCK_PATIENTS;
DROP USER MOCKDB;