BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE MOCKDB.MOCK_USERS';
  EXECUTE IMMEDIATE 'DROP TABLE MOCKDB.MOCK_USER_PAT_ID';
  EXECUTE IMMEDIATE 'DROP TABLE MOCKDB.MOCK_PATIENTS';
  EXECUTE IMMEDIATE 'DROP TABLE MOCKDB.DATABASECHANGELOG';
  EXECUTE IMMEDIATE 'DROP TABLE MOCKDB.DATABASECHANGELOGLOCK';
  EXECUTE IMMEDIATE 'DROP USER MOCKDB';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;

