CREATE BIGFILE TABLESPACE VARDB DATAFILE 'vardb.dat' SIZE 10M AUTOEXTEND ON;

CREATE USER VARDB IDENTIFIED BY Agilexadmin99$ DEFAULT TABLESPACE VARDB;
GRANT CONNECT, RESOURCE, DBA to VARDB;
GRANT CREATE SESSION TO VARDB;
GRANT UNLIMITED TABLESPACE TO VARDB;

--------------------------------------------------------
--  DDL for Table APPOINTMENT_METRICS
--------------------------------------------------------

  CREATE TABLE "VARDB"."APPOINTMENT_METRICS"
   (	"NAME" VARCHAR2(100 BYTE),
	"VALUE" NUMBER(9,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Table APPOINTMENT_REQUEST
--------------------------------------------------------

  CREATE TABLE "VARDB"."APPOINTMENT_REQUEST"
   (	"APPOINTMENT_REQUEST_ID" VARCHAR2(32 BYTE),
	"PATIENT_ID" VARCHAR2(255 BYTE),
	"LAST_UPDATED_DATE" TIMESTAMP (6),
	"CREATED_DATE" TIMESTAMP (6),
	"DELETED_DATE" TIMESTAMP (6),
	"ACTIVE" NUMBER(1,0),
	"SECOND_REQUEST" NUMBER(1,0),
	"APPOINTMENT_DATE" VARCHAR2(50 BYTE),
	"APPOINTMENT_TIME" VARCHAR2(50 BYTE),
	"OPTION_DATE_1" VARCHAR2(50 BYTE),
	"OPTION_TIME_1" VARCHAR2(50 BYTE),
	"OPTION_DATE_2" VARCHAR2(50 BYTE),
	"OPTION_TIME_2" VARCHAR2(50 BYTE),
	"OPTION_DATE_3" VARCHAR2(50 BYTE),
	"OPTION_TIME_3" VARCHAR2(50 BYTE),
	"STATUS" VARCHAR2(255 BYTE),
	"APPOINTMENT_TYPE" VARCHAR2(255 BYTE),
	"FACILITY_CODE" VARCHAR2(100 BYTE),
	"EMAIL" VARCHAR2(255 BYTE),
	"PHONE_NUMBER" VARCHAR2(255 BYTE),
	"TEXT_MESSAGING_ALLOWED" NUMBER(1,0),
	"TEXT_MESSAGING_PHONE_NUMBER" VARCHAR2(255 BYTE),
	"PURPOSE_OF_VISIT" VARCHAR2(255 BYTE),
	"OTHER_PURPOSE_OF_VISIT" VARCHAR2(100 BYTE),
	"VISIT_TYPE" VARCHAR2(40 BYTE),
	"PROVIDER_ID" VARCHAR2(255 BYTE),
	"PROVIDER_NAME" VARCHAR2(255 BYTE),
	"PROVIDER_PERSON_CLASS" VARCHAR2(255 BYTE),
	"PROVIDER_OPTION" VARCHAR2(100 BYTE),
	"SECOND_REQUEST_SUBMITTED" NUMBER(1,0),
	"PARENT_REQUEST_ID" VARCHAR2(32 BYTE),
	"HAS_VETERAN_NEW_MESSAGE" NUMBER(1,0) DEFAULT 0,
	"HAS_PROVIDER_NEW_MESSAGE" NUMBER(1,0) DEFAULT 0,
	"PROVIDER_SEEN_APPT_REQ" NUMBER(1,0) DEFAULT 0,
	"REQUESTED_PHONE_CALL" NUMBER(1,0) DEFAULT 0,
	"TYPE_OF_CARE_ID" VARCHAR2(50 BYTE),
	"REASON_FOR_VISIT" VARCHAR2(50 BYTE),
	"OTHER_REASON_FOR_VISIT" VARCHAR2(255 BYTE),
	"ADDITIONAL_INFORMATION" VARCHAR2(255 BYTE),
	"BOOKED_APPT_DATETIME" TIMESTAMP (6),
	"LOCATION_ID" VARCHAR2(100 BYTE),
	"AUTHORITATIVE_NAME" VARCHAR2(255 BYTE),
	"FRIENDLY_NAME" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Table APPOINTMENT_REQUEST_MESSAGE
--------------------------------------------------------

  CREATE TABLE "VARDB"."APPOINTMENT_REQUEST_MESSAGE"
   (	"ID" VARCHAR2(32 BYTE),
	"APPOINTMENT_REQUEST_ID" VARCHAR2(32 BYTE),
	"SENDER_ID" VARCHAR2(255 BYTE),
	"MESSAGE_TEXT" VARCHAR2(255 BYTE),
	"MESSAGE_DATE_TIME" TIMESTAMP (6),
	"MESSAGE_TYPE" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Table APPT_REQ_INPROCESS
--------------------------------------------------------

  CREATE TABLE "VARDB"."APPT_REQ_INPROCESS"
   (	"APPT_REQ_ID" VARCHAR2(32 BYTE),
	"USER_ID" VARCHAR2(255 BYTE),
	"FIRST_NAME" VARCHAR2(255 BYTE),
	"LAST_NAME" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Table AR_DETAIL_CODE
--------------------------------------------------------

  CREATE TABLE "VARDB"."AR_DETAIL_CODE"
   (	"AR_DETAIL_CODE_ID" VARCHAR2(32 BYTE),
	"DETAIL_CODE_ID" VARCHAR2(32 BYTE),
	"APPOINTMENT_REQUEST_ID" VARCHAR2(32 BYTE),
	"CREATED_DATE" TIMESTAMP (6),
	"USER_ID" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Table BEST_TIME_TO_CALL
--------------------------------------------------------

  CREATE TABLE "VARDB"."BEST_TIME_TO_CALL"
   (	"APPOINTMENT_REQUEST_ID" VARCHAR2(32 BYTE),
	"BEST_TIME" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Table CC_APPOINTMENT_REQUEST
--------------------------------------------------------

  CREATE TABLE "VARDB"."CC_APPOINTMENT_REQUEST"
   (	"CC_APPOINTMENT_REQUEST_ID" VARCHAR2(32 BYTE),
	"APPOINTMENT_REQUEST_ID" VARCHAR2(32 BYTE),
	"TRAVEL_BURDEN" NUMBER,
	"UNUSUAL_TRAVEL_BURDEN" NUMBER,
	"DISTANCE_WILLING_TO_TRAVEL" NUMBER,
	"ADDRESS" VARCHAR2(100 BYTE),
	"CITY" VARCHAR2(50 BYTE),
	"STATE" VARCHAR2(2 BYTE),
	"ZIPCODE" VARCHAR2(5 BYTE),
	"PREFERRED_ZIPCODE" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
  --------------------------------------------------------
--  DDL for Table DATABASECHANGELOG
--------------------------------------------------------

  CREATE TABLE "VARDB"."DATABASECHANGELOG"
   (	"ID" VARCHAR2(63 BYTE),
	"AUTHOR" VARCHAR2(63 BYTE),
	"FILENAME" VARCHAR2(200 BYTE),
	"DATEEXECUTED" TIMESTAMP (6),
	"ORDEREXECUTED" NUMBER(*,0),
	"EXECTYPE" VARCHAR2(10 BYTE),
	"MD5SUM" VARCHAR2(35 BYTE),
	"DESCRIPTION" VARCHAR2(255 BYTE),
	"COMMENTS" VARCHAR2(255 BYTE),
	"TAG" VARCHAR2(255 BYTE),
	"LIQUIBASE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Table DATABASECHANGELOGLOCK
--------------------------------------------------------

  CREATE TABLE "VARDB"."DATABASECHANGELOGLOCK"
   (	"ID" NUMBER(*,0),
	"LOCKED" NUMBER(1,0),
	"LOCKGRANTED" TIMESTAMP (6),
	"LOCKEDBY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Table DETAIL_CODE
--------------------------------------------------------

  CREATE TABLE "VARDB"."DETAIL_CODE"
   (	"DETAIL_CODE_ID" VARCHAR2(32 BYTE),
	"PROVIDER_MESSAGE" VARCHAR2(2000 BYTE),
	"VETERAN_MESSAGE" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Table FACILITY
--------------------------------------------------------

  CREATE TABLE "VARDB"."FACILITY"
   (	"NAME" VARCHAR2(100 BYTE),
	"TYPE" VARCHAR2(100 BYTE),
	"FACILITY_CODE" VARCHAR2(100 BYTE),
	"STATE" VARCHAR2(50 BYTE),
	"CITY" VARCHAR2(50 BYTE),
	"ADDRESS" VARCHAR2(100 BYTE),
	"PARENT_SITE_CODE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Table NOTIFICATION_PREFERENCE
--------------------------------------------------------

  CREATE TABLE "VARDB"."NOTIFICATION_PREFERENCE"
   (	"PATIENT_ID" VARCHAR2(255 BYTE),
	"NOTIFICATION_FREQUENCY" VARCHAR2(255 BYTE),
	"EMAIL_ALLOWED" NUMBER(1,0),
	"EMAIL_ADDRESS" VARCHAR2(255 BYTE),
	"TEXT_MESSAGING_ALLOWED" NUMBER(1,0),
	"TEXT_MESSAGING_PHONE_NUMBER" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Table PATIENT
--------------------------------------------------------

  CREATE TABLE "VARDB"."PATIENT"
   (	"PATIENT_ID" VARCHAR2(255 BYTE),
	"FIRST_NAME" VARCHAR2(100 BYTE),
	"LAST_NAME" VARCHAR2(100 BYTE),
	"SSN" VARCHAR2(20 BYTE),
	"DATE_OF_BIRTH" TIMESTAMP (6),
	"TEXT_MESSAGING_ALLOWED" NUMBER(1,0),
	"TEXT_MESSAGING_PHONE_NUMBER" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Table PATIENT_METADATA
--------------------------------------------------------

  CREATE TABLE "VARDB"."PATIENT_METADATA"
   (	"PATIENT_ID" VARCHAR2(255 BYTE),
	"LAST_APPT_REQ_ACCESS_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Table USER_FEEDBACK
--------------------------------------------------------

  CREATE TABLE "VARDB"."USER_FEEDBACK"
   (	"USER_FEEDBACK_ID" VARCHAR2(32 BYTE),
	"RATING" NUMBER(3,0),
	"APPT_PROCESSED_TIMELY" VARCHAR2(32 BYTE),
	"COMMENTS" CLOB,
	"CREATED_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB"
 LOB ("COMMENTS") STORE AS BASICFILE (
  TABLESPACE "VARDB" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table USER_HISTORY
--------------------------------------------------------

  CREATE TABLE "VARDB"."USER_HISTORY"
   (	"ID" RAW(16),
	"USER_ID" VARCHAR2(255 BYTE),
	"TABLE_NAME" VARCHAR2(255 BYTE),
	"ROW_ID" RAW(16),
	"OPERATION" VARCHAR2(255 BYTE),
	"ACTION_DATE" TIMESTAMP (6),
	"DATA" CLOB
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB"
 LOB ("DATA") STORE AS BASICFILE (
  TABLESPACE "VARDB" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index PK_NOTIFICATION_PREFERENCE
--------------------------------------------------------

  CREATE UNIQUE INDEX "VARDB"."PK_NOTIFICATION_PREFERENCE" ON "VARDB"."NOTIFICATION_PREFERENCE" ("PATIENT_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Index USER_HISTORY_IDX_USER_ID
--------------------------------------------------------

  CREATE INDEX "VARDB"."USER_HISTORY_IDX_USER_ID" ON "VARDB"."USER_HISTORY" ("USER_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Index PK_DATABASECHANGELOGLOCK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VARDB"."PK_DATABASECHANGELOGLOCK" ON "VARDB"."DATABASECHANGELOGLOCK" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Index PK_FACILITY
--------------------------------------------------------

  CREATE UNIQUE INDEX "VARDB"."PK_FACILITY" ON "VARDB"."FACILITY" ("NAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Index PK_DETAIL_CODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "VARDB"."PK_DETAIL_CODE" ON "VARDB"."DETAIL_CODE" ("DETAIL_CODE_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Index PK_DATABASECHANGELOG
--------------------------------------------------------

  CREATE UNIQUE INDEX "VARDB"."PK_DATABASECHANGELOG" ON "VARDB"."DATABASECHANGELOG" ("ID", "AUTHOR", "FILENAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Index PK_APPT_REQ_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "VARDB"."PK_APPT_REQ_ID" ON "VARDB"."APPT_REQ_INPROCESS" ("APPT_REQ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Index PK_BEST_TIME
--------------------------------------------------------

  CREATE UNIQUE INDEX "VARDB"."PK_BEST_TIME" ON "VARDB"."BEST_TIME_TO_CALL" ("APPOINTMENT_REQUEST_ID", "BEST_TIME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Index USER_HISTORY_IDX_ACTION_DATE
--------------------------------------------------------

  CREATE INDEX "VARDB"."USER_HISTORY_IDX_ACTION_DATE" ON "VARDB"."USER_HISTORY" ("ACTION_DATE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Index PK_PATIENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "VARDB"."PK_PATIENT" ON "VARDB"."PATIENT" ("PATIENT_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Index PK_USER_FEEDBACK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "VARDB"."PK_USER_FEEDBACK_ID" ON "VARDB"."USER_FEEDBACK" ("USER_FEEDBACK_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Index PK_APPOINTMENT_REQUEST
--------------------------------------------------------

  CREATE UNIQUE INDEX "VARDB"."PK_APPOINTMENT_REQUEST" ON "VARDB"."APPOINTMENT_REQUEST" ("APPOINTMENT_REQUEST_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Index USER_HISTORY_PK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "VARDB"."USER_HISTORY_PK_ID" ON "VARDB"."USER_HISTORY" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Index APPOINTMENT_CC_REQUEST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VARDB"."APPOINTMENT_CC_REQUEST_PK" ON "VARDB"."CC_APPOINTMENT_REQUEST" ("CC_APPOINTMENT_REQUEST_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Index PK_ARDC_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "VARDB"."PK_ARDC_ID" ON "VARDB"."AR_DETAIL_CODE" ("AR_DETAIL_CODE_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Index APPT_REQ_MSG_PK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "VARDB"."APPT_REQ_MSG_PK_ID" ON "VARDB"."APPOINTMENT_REQUEST_MESSAGE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  DDL for Index PK_PATIENT_METADATA_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "VARDB"."PK_PATIENT_METADATA_ID" ON "VARDB"."PATIENT_METADATA" ("PATIENT_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB" ;
--------------------------------------------------------
--  Constraints for Table FACILITY
--------------------------------------------------------

  ALTER TABLE "VARDB"."FACILITY" ADD CONSTRAINT "PK_FACILITY" PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB"  ENABLE;
  ALTER TABLE "VARDB"."FACILITY" MODIFY ("PARENT_SITE_CODE" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."FACILITY" MODIFY ("FACILITY_CODE" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."FACILITY" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DATABASECHANGELOGLOCK
--------------------------------------------------------

  ALTER TABLE "VARDB"."DATABASECHANGELOGLOCK" ADD CONSTRAINT "PK_DATABASECHANGELOGLOCK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB"  ENABLE;
  ALTER TABLE "VARDB"."DATABASECHANGELOGLOCK" MODIFY ("LOCKED" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."DATABASECHANGELOGLOCK" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BEST_TIME_TO_CALL
--------------------------------------------------------

  ALTER TABLE "VARDB"."BEST_TIME_TO_CALL" ADD CONSTRAINT "PK_BEST_TIME" PRIMARY KEY ("APPOINTMENT_REQUEST_ID", "BEST_TIME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB"  ENABLE;
  ALTER TABLE "VARDB"."BEST_TIME_TO_CALL" MODIFY ("BEST_TIME" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."BEST_TIME_TO_CALL" MODIFY ("APPOINTMENT_REQUEST_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PATIENT
--------------------------------------------------------

  ALTER TABLE "VARDB"."PATIENT" ADD CONSTRAINT "PK_PATIENT" PRIMARY KEY ("PATIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB"  ENABLE;
  ALTER TABLE "VARDB"."PATIENT" MODIFY ("TEXT_MESSAGING_ALLOWED" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."PATIENT" MODIFY ("DATE_OF_BIRTH" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."PATIENT" MODIFY ("SSN" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."PATIENT" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."PATIENT" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."PATIENT" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETAIL_CODE
--------------------------------------------------------

  ALTER TABLE "VARDB"."DETAIL_CODE" ADD CONSTRAINT "PK_DETAIL_CODE" PRIMARY KEY ("DETAIL_CODE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB"  ENABLE;
  ALTER TABLE "VARDB"."DETAIL_CODE" MODIFY ("VETERAN_MESSAGE" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."DETAIL_CODE" MODIFY ("PROVIDER_MESSAGE" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."DETAIL_CODE" MODIFY ("DETAIL_CODE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AR_DETAIL_CODE
--------------------------------------------------------

  ALTER TABLE "VARDB"."AR_DETAIL_CODE" ADD CONSTRAINT "PK_ARDC_ID" PRIMARY KEY ("AR_DETAIL_CODE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB"  ENABLE;
  ALTER TABLE "VARDB"."AR_DETAIL_CODE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."AR_DETAIL_CODE" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."AR_DETAIL_CODE" MODIFY ("APPOINTMENT_REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."AR_DETAIL_CODE" MODIFY ("DETAIL_CODE_ID" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."AR_DETAIL_CODE" MODIFY ("AR_DETAIL_CODE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTIFICATION_PREFERENCE
--------------------------------------------------------

  ALTER TABLE "VARDB"."NOTIFICATION_PREFERENCE" ADD CONSTRAINT "PK_NOTIFICATION_PREFERENCE" PRIMARY KEY ("PATIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB"  ENABLE;
  ALTER TABLE "VARDB"."NOTIFICATION_PREFERENCE" MODIFY ("TEXT_MESSAGING_ALLOWED" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."NOTIFICATION_PREFERENCE" MODIFY ("EMAIL_ALLOWED" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."NOTIFICATION_PREFERENCE" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PATIENT_METADATA
--------------------------------------------------------

  ALTER TABLE "VARDB"."PATIENT_METADATA" ADD CONSTRAINT "PK_PATIENT_METADATA_ID" PRIMARY KEY ("PATIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB"  ENABLE;
  ALTER TABLE "VARDB"."PATIENT_METADATA" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DATABASECHANGELOG
--------------------------------------------------------

  ALTER TABLE "VARDB"."DATABASECHANGELOG" ADD CONSTRAINT "PK_DATABASECHANGELOG" PRIMARY KEY ("ID", "AUTHOR", "FILENAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB"  ENABLE;
  ALTER TABLE "VARDB"."DATABASECHANGELOG" MODIFY ("EXECTYPE" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."DATABASECHANGELOG" MODIFY ("ORDEREXECUTED" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."DATABASECHANGELOG" MODIFY ("DATEEXECUTED" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."DATABASECHANGELOG" MODIFY ("FILENAME" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."DATABASECHANGELOG" MODIFY ("AUTHOR" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."DATABASECHANGELOG" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APPT_REQ_INPROCESS
--------------------------------------------------------

  ALTER TABLE "VARDB"."APPT_REQ_INPROCESS" ADD CONSTRAINT "PK_APPT_REQ_ID" PRIMARY KEY ("APPT_REQ_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB"  ENABLE;
  ALTER TABLE "VARDB"."APPT_REQ_INPROCESS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPT_REQ_INPROCESS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPT_REQ_INPROCESS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPT_REQ_INPROCESS" MODIFY ("APPT_REQ_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CC_APPOINTMENT_REQUEST
--------------------------------------------------------

  ALTER TABLE "VARDB"."CC_APPOINTMENT_REQUEST" MODIFY ("CC_APPOINTMENT_REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."CC_APPOINTMENT_REQUEST" MODIFY ("APPOINTMENT_REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."CC_APPOINTMENT_REQUEST" MODIFY ("TRAVEL_BURDEN" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."CC_APPOINTMENT_REQUEST" MODIFY ("DISTANCE_WILLING_TO_TRAVEL" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."CC_APPOINTMENT_REQUEST" MODIFY ("PREFERRED_ZIPCODE" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."CC_APPOINTMENT_REQUEST" ADD CONSTRAINT "APPOINTMENT_CC_REQUEST_PK" PRIMARY KEY ("CC_APPOINTMENT_REQUEST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table APPOINTMENT_REQUEST
--------------------------------------------------------

  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST" ADD CONSTRAINT "PK_APPOINTMENT_REQUEST" PRIMARY KEY ("APPOINTMENT_REQUEST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB"  ENABLE;
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST" MODIFY ("SECOND_REQUEST_SUBMITTED" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST" MODIFY ("PROVIDER_NAME" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST" MODIFY ("PROVIDER_ID" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST" MODIFY ("VISIT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST" MODIFY ("PURPOSE_OF_VISIT" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST" MODIFY ("TEXT_MESSAGING_ALLOWED" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST" MODIFY ("FACILITY_CODE" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST" MODIFY ("APPOINTMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST" MODIFY ("OPTION_TIME_3" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST" MODIFY ("OPTION_DATE_3" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST" MODIFY ("OPTION_TIME_2" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST" MODIFY ("OPTION_DATE_2" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST" MODIFY ("OPTION_TIME_1" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST" MODIFY ("OPTION_DATE_1" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST" MODIFY ("SECOND_REQUEST" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST" MODIFY ("ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST" MODIFY ("LAST_UPDATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST" MODIFY ("APPOINTMENT_REQUEST_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APPOINTMENT_REQUEST_MESSAGE
--------------------------------------------------------

  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST_MESSAGE" ADD CONSTRAINT "APPT_REQ_MSG_PK_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB"  ENABLE;
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST_MESSAGE" MODIFY ("MESSAGE_DATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST_MESSAGE" MODIFY ("MESSAGE_TEXT" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST_MESSAGE" MODIFY ("SENDER_ID" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST_MESSAGE" MODIFY ("APPOINTMENT_REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."APPOINTMENT_REQUEST_MESSAGE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_HISTORY
--------------------------------------------------------

  ALTER TABLE "VARDB"."USER_HISTORY" ADD CONSTRAINT "USER_HISTORY_PK_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB"  ENABLE;
  ALTER TABLE "VARDB"."USER_HISTORY" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_FEEDBACK
--------------------------------------------------------

  ALTER TABLE "VARDB"."USER_FEEDBACK" ADD CONSTRAINT "PK_USER_FEEDBACK_ID" PRIMARY KEY ("USER_FEEDBACK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VARDB"  ENABLE;
  ALTER TABLE "VARDB"."USER_FEEDBACK" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."USER_FEEDBACK" MODIFY ("APPT_PROCESSED_TIMELY" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."USER_FEEDBACK" MODIFY ("RATING" NOT NULL ENABLE);
  ALTER TABLE "VARDB"."USER_FEEDBACK" MODIFY ("USER_FEEDBACK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table AR_DETAIL_CODE
--------------------------------------------------------

  ALTER TABLE "VARDB"."AR_DETAIL_CODE" ADD CONSTRAINT "FK_ARDC_APPT_REQ_ID" FOREIGN KEY ("APPOINTMENT_REQUEST_ID")
    REFERENCES "VARDB"."APPOINTMENT_REQUEST" ("APPOINTMENT_REQUEST_ID") ENABLE;
  ALTER TABLE "VARDB"."AR_DETAIL_CODE" ADD CONSTRAINT "FK_ARDC_DETAIL_CODE" FOREIGN KEY ("DETAIL_CODE_ID")
    REFERENCES "VARDB"."DETAIL_CODE" ("DETAIL_CODE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BEST_TIME_TO_CALL
--------------------------------------------------------

  ALTER TABLE "VARDB"."BEST_TIME_TO_CALL" ADD CONSTRAINT "FK_BTTC_APPT_REQ_ID" FOREIGN KEY ("APPOINTMENT_REQUEST_ID")
    REFERENCES "VARDB"."APPOINTMENT_REQUEST" ("APPOINTMENT_REQUEST_ID") ENABLE;