
ALTER TABLE "VARDB"."CC_APPOINTMENT_REQUEST"
MODIFY (
    TRAVEL_BURDEN NULL
);
ALTER TABLE "VARDB"."CC_APPOINTMENT_REQUEST"
ADD (
    DISTANCE_ELIGIBLE NUMBER
);
UPDATE "VARDB"."CC_APPOINTMENT_REQUEST"
SET DISTANCE_ELIGIBLE = 0;
ALTER TABLE "VARDB"."CC_APPOINTMENT_REQUEST"
MODIFY (
    DISTANCE_ELIGIBLE NOT NULL
);

ALTER TABLE VARDB.APPOINTMENT_REQUEST
ADD (
        LOCATION_ID VARCHAR2(100),
        AUTHORITATIVE_NAME VARCHAR2(255),
        FRIENDLY_NAME VARCHAR2(255)
    );
COMMIT;